#!/usr/bin/env python3
"""THRENOS content build: art + world data -> ca65 source in src/gen/."""
import os
import sys
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
GEN = ROOT / "src" / "gen"
sys.path.insert(0, str(HERE))

from chrlib import ChrRom, emit_chr_asm, tile_from_rows      # noqa: E402
import font                                                   # noqa: E402
import chars                                                  # noqa: E402
import art_tiles                                              # noqa: E402
import world                                                  # noqa: E402
import areas                                                  # noqa: E402
from maps import emit_maps                                    # noqa: E402
import text_compile                                           # noqa: E402
import script_text                                            # noqa: E402
import emit_data                                              # noqa: E402
import gamedata                                               # noqa: E402
import monster_art                                            # noqa: E402
from chrlib import grid_to_tiles                              # noqa: E402
import music                                                   # noqa: E402
import songs                                                   # noqa: E402

# --- CHR bank allocation (1KB units) -----------------------------------------
CHR_FONT = 0            # resident BG $00-$3F: font, frame, cursor
CHR_UI = 1              # resident BG $40-$7F: bars, icons
CHR_TILESET_BASE = 2    # 2 banks per tileset -> BG $80-$FF
CHR_SPRITE0 = 88        # 2KB sprite bank at $1000
CHR_SPRITE1 = 90        # 2KB sprite bank at $1800

# --- PRG bank allocation ------------------------------------------------------
BANK_TILESETS = 9
BANK_WORLD = 8
BANK_AREA = [4, 5, 6, 7]
BANK_TEXT_BASE = 0
BANK_TABLES = 10
CHR_MONSTER_BASE = 32
SOUND_BANK = 24         # the music data rides along in the driver's own bank


def solid_tile(c):
    return tile_from_rows([c * 8] * 8)


def build_ui_bank():
    t = [solid_tile('.'), solid_tile('1'), solid_tile('2'), solid_tile('3')]
    for n in range(9):                       # $44-$4C: 8-step bar fill
        rows = ["........"]
        rows += ["3" * n + "." * (8 - n)] * 6
        rows += ["........"]
        t.append(tile_from_rows(rows))
    while len(t) < 64:
        t.append(bytes(16))
    return t


def emit_tilesets(chr_rom, tilesets):
    """Place tileset CHR and write src/gen/tilesets.s + constants."""
    lines = ["; GENERATED by tools/build.py\n", '.include "banks.inc"\n',
             '.export tset_data_start\n', f'.segment "BANK{BANK_TILESETS:02d}"\n',
             "tset_data_start:\n"]
    consts = []
    addrs = []
    for i, c in enumerate(tilesets):
        a = CHR_TILESET_BASE + 2 * i
        chr_rom.put_span(a, c["tiles"], f"ts-{c['name']}")
        consts.append(f"TS_{c['name'].upper()} = {i}")
        addrs.append(f"ts_{c['name']}")
        pal = []
        for p in c["palettes"]:
            pal += [0x0F] + list(p)
        pal += [0x0F, 0x00, 0x10, 0x30]      # sub-palette 3 is always the UI one
        lines.append(f"\n.export ts_{c['name']}\n")
        lines.append(f"ts_{c['name']}:\n")
        lines.append(f"    .byte {a}, {a + 1}, {c['n']}\n")
        lines.append("    .byte " + ",".join(f"${v:02X}" for v in pal) + "\n")
        for key in ("tl", "tr", "bl", "br", "attr", "prop"):
            v = c[key]
            for j in range(0, 128, 16):
                lines.append("    .byte " + ",".join(f"${b:02X}" for b in v[j:j + 16]) + "\n")
    (GEN / "tilesets.s").write_text("".join(lines))
    return consts, addrs


def build():
    GEN.mkdir(parents=True, exist_ok=True)
    chr_rom = ChrRom(128)
    chr_rom.put_bank(CHR_FONT, font.build_font_bank(), "font")
    chr_rom.put_bank(CHR_UI, build_ui_bank(), "ui")
    chr_rom.put_span(CHR_SPRITE0, chars.build_sprite_bank(), "sprites")

    ts_over = art_tiles.overworld()
    ts_town = art_tiles.town()
    ts_dun = art_tiles.dungeon()
    compiled = [ts_over.compile(), ts_town.compile(), ts_dun.compile()]
    consts, ts_addrs = emit_tilesets(chr_rom, compiled)


    # --- maps ----------------------------------------------------------------
    ow = world.overworld_map(ts_over)
    if hasattr(areas, "build_all"):
        area_maps = areas.build_all(ts_town, ts_dun)
    else:                       # areas.py mid-edit: keep the build linkable
        import areas_fallback
        print("  (areas.py has no build_all yet - using placeholder rooms)")
        area_maps = areas_fallback.build_all(ts_town, ts_dun)

    with open(GEN / "maps_world.s", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        f.write('.include "banks.inc"\n')
        for c in consts:
            f.write(c + "\n")
        f.write(f'.segment "BANK{BANK_WORLD:02d}"\n')
        f.write(".export map_OVERWORLD\n")
        emit_maps(f, [ow])

    # pack area maps into the area banks, largest-first, 8KB each
    banks = {b: [] for b in BANK_AREA}
    used = {b: 0 for b in BANK_AREA}
    placed = {}
    for m in area_maps:
        sz = m.size_estimate()
        for b in BANK_AREA:
            if used[b] + sz < 8100:
                banks[b].append(m)
                used[b] += sz
                placed[m.name] = b
                break
        else:
            raise RuntimeError(f"no room for map {m.name} ({sz} bytes)")

    with open(GEN / "maps_area.s", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        f.write('.include "banks.inc"\n')
        for c in consts:
            f.write(c + "\n")
        for b in BANK_AREA:
            if not banks[b]:
                continue
            f.write(f'\n.segment "BANK{b:02d}"\n')
            for m in banks[b]:
                f.write(f".export map_{m.name}\n")
            emit_maps(f, banks[b])

    # --- engine-bank tables ---------------------------------------------------
    with open(GEN / "tables.s", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        f.write('.include "banks.inc"\n')
        f.write(".export map_bank_tab, map_addr_tab, tset_bank_tab, tset_addr_tab\n")
        f.write(".export spr_palette\n")
        for a in ts_addrs:
            f.write(f".import {a}\n")
        for n in world.MAP_NAMES:
            f.write(f".import map_{n}\n")
        f.write('.segment "ENGRO"\n')
        f.write("map_bank_tab:\n    .byte " + ",".join(
            str(BANK_WORLD if n == "OVERWORLD" else placed[n])
            for n in world.MAP_NAMES) + "\n")
        f.write("map_addr_tab:\n")
        for n in world.MAP_NAMES:
            f.write(f"    .addr map_{n}\n")
        f.write(f"tset_bank_tab:\n    .byte " +
                ",".join([str(BANK_TILESETS)] * len(ts_addrs)) + "\n")
        f.write("tset_addr_tab:\n")
        for a in ts_addrs:
            f.write(f"    .addr {a}\n")
        f.write("spr_palette:\n    .byte " +
                ",".join(f"${v:02X}" for v in chars.SPRITE_PALETTE) + "\n")

    # --- script --------------------------------------------------------------
    msg_ids, text_banks = text_compile.compile_all(script_text.MESSAGES)
    with open(GEN / "text.s", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        f.write('.include "banks.inc"\n')
        text_compile.emit(f, text_banks, BANK_TEXT_BASE)
    with open(GEN / "msgids.inc", "w") as f:
        f.write("; GENERATED by tools/build.py - message ids\n")
        for name, i in msg_ids.items():
            f.write(f"{name} = {i}\n")

    # --- monsters: one 1KB CHR bank each --------------------------------------
    mon_sizes = []
    for i, m in enumerate(gamedata.MONSTERS):
        art = monster_art.MONSTERS[gamedata.art_key(m[0])]
        px = art["size"]
        tiles = grid_to_tiles(art["art"], px // 8, px // 8)
        chr_rom.put_bank(CHR_MONSTER_BASE + i, tiles, f"mon-{m[0]}")
        mon_sizes.append(px // 8)

    # --- numeric game data ----------------------------------------------------
    with open(GEN / "data.s", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        f.write('.include "banks.inc"\n')
        emit_data.emit(f, BANK_TABLES, mon_sizes)
    with open(GEN / "dataids.inc", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        emit_data.emit_consts(f)
        f.write(f"CHR_MONSTER_BASE = {CHR_MONSTER_BASE}\n")

    # --- music ----------------------------------------------------------------
    md = music.compile_all(songs.SONGS, songs.INSTRUMENTS,
                           songs.ENVELOPES, songs.SFX)
    with open(GEN / "music.s", "w") as f:
        f.write("; GENERATED by tools/build.py\n")
        music.emit(f, md, SOUND_BANK)
    with open(GEN / "songids.inc", "w") as f:
        f.write("; GENERATED by tools/build.py - song and sfx ids\n")
        music.emit_ids(f, md)

    # --- ca65 charmap ---------------------------------------------------------
    with open(GEN / "charmap.inc", "w") as f:
        f.write("; GENERATED by tools/build.py - ASCII -> font tile index\n")
        for i, c in enumerate(font.CHARSET):
            f.write(f".charmap ${ord(c):02X}, ${i:02X}\n")
            if c.isalpha():
                f.write(f".charmap ${ord(c.lower()):02X}, ${i:02X}\n")
        f.write("STR_END = $FF\n")
        f.write(f"DIGIT0 = ${font.CHARSET.index('0'):02X}\n")
        f.write(f"TILE_ARROW = ${font.TILE_ARROW:02X}\n")
        f.write(f"TILE_CURSOR = ${font.TILE_CURSOR:02X}\n")
        f.write(f"TILE_FRAME = ${font.TILE_FRAME:02X}\n")

    # --- report ---------------------------------------------------------------
    print(f"tilesets: " + ", ".join(
        f"{c['name']}({c['n']}mt/{c['ntiles']}tiles)" for c in compiled))
    print(f"overworld: {ow.w}x{ow.h}, {ow.size_estimate()} bytes")
    for b in BANK_AREA:
        if banks[b]:
            print(f"  bank {b}: {used[b]:5d} bytes, {len(banks[b])} maps")
    emit_chr_asm(chr_rom, GEN / "chr.s")
    print(f"CHR banks used: {sum(chr_rom.used)}")
    print(f"script: {len(msg_ids)} messages in {len(text_banks)} banks")
    print(f"game data: ~{emit_data.size_estimate()} bytes in bank {BANK_TABLES}")
    sz = md["sizes"]
    print(f"music: {len(md['songs'])} songs, {len(md['sfx'])} sfx, "
          f"{len(md['patterns'])} patterns, {sz['total']} bytes in "
          f"bank {SOUND_BANK} (" +
          ", ".join(f"{k} {v}" for k, v in sz.items() if k != "total") + ")")


if __name__ == "__main__":
    build()
