#!/usr/bin/env python3
"""THRENOS content build: art + data -> ca65 source in src/gen/.

Run from anywhere:  python3 game/tools/build.py
"""
import os
import sys
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
GEN = ROOT / "src" / "gen"
sys.path.insert(0, str(HERE))

from chrlib import ChrRom, emit_chr_asm, tile_from_rows        # noqa: E402
import font                                                     # noqa: E402

# --- CHR bank allocation (1KB units) -----------------------------------------
CHR_FONT = 0            # resident: font, frame, cursor  (BG $00-$3F)
CHR_UI = 1              # resident: HUD, shared art      (BG $40-$7F)
CHR_TILESET0 = 2        # first area tileset             (BG $80-$FF, 2 banks)
CHR_SPRITE0 = 88        # 2KB sprite bank at $1000
CHR_SPRITE1 = 90        # 2KB sprite bank at $1800
CHR_TEST_HI = 100       # high-bank banking proof


def solid_tile(c):
    return tile_from_rows([c * 8] * 8)


def build_ui_bank():
    """Resident BG bank 1 ($40-$7F): bars, icons, and solid blocks."""
    t = []
    t.append(solid_tile('.'))                 # $40 solid backdrop
    t.append(solid_tile('1'))                 # $41 solid colour 1
    t.append(solid_tile('2'))                 # $42 solid colour 2
    t.append(solid_tile('3'))                 # $43 solid colour 3
    # $44-$4B: an 8-step horizontal bar fill (HP/TP meters)
    for n in range(8):
        rows = ["........"]
        body = "3" * n + "." * (8 - n)
        rows += [body] * 6
        rows += ["........"]
        t.append(tile_from_rows(rows))
    while len(t) < 64:
        t.append(bytes(16))
    return t


def build():
    GEN.mkdir(parents=True, exist_ok=True)
    chr_rom = ChrRom(128)
    chr_rom.put_bank(CHR_FONT, font.build_font_bank(), "font")
    chr_rom.put_bank(CHR_UI, build_ui_bank(), "ui")

    # --- step-0 banking proof art -------------------------------------------
    box = ["33333333", "3......3", "3.3333.3", "3.3..3.3",
           "3.3..3.3", "3.3333.3", "3......3", "33333333"]
    diag = ["3......3", ".3....3.", "..3..3..", "...33...",
            "...33...", "..3..3..", ".3....3.", "3......3"]
    checker = ["3.3.3.3.", ".3.3.3.3", "3.3.3.3.", ".3.3.3.3",
               "3.3.3.3.", ".3.3.3.3", "3.3.3.3.", ".3.3.3.3"]
    chr_rom.put_bank(CHR_TILESET0, [tile_from_rows(box)] + [bytes(16)] * 63, "test-box")
    chr_rom.put_bank(CHR_TILESET0 + 1, [tile_from_rows(checker)] + [bytes(16)] * 63, "test-chk")
    chr_rom.put_bank(CHR_TEST_HI, [tile_from_rows(diag)] + [bytes(16)] * 63, "test-hi")

    n = emit_chr_asm(chr_rom, GEN / "chr.s")

    # --- ca65 charmap: ASCII string literals assemble to font tile indices ---
    with open(GEN / "charmap.inc", "w") as f:
        f.write("; GENERATED by tools/build.py - ASCII -> font tile index\n")
        for i, c in enumerate(font.CHARSET):
            f.write(f".charmap ${ord(c):02X}, ${i:02X}\n")
            if c.isalpha():
                f.write(f".charmap ${ord(c.lower()):02X}, ${i:02X}\n")
        f.write(f"STR_END = $FF\n")
        f.write(f"DIGIT0 = ${font.CHARSET.index('0'):02X}\n")
        f.write(f"LETTER_A = ${font.CHARSET.index('A'):02X}\n")
        f.write(f"TILE_ARROW = ${font.TILE_ARROW:02X}\n")
        f.write(f"TILE_CURSOR = ${font.TILE_CURSOR:02X}\n")
        f.write(f"TILE_FRAME = ${font.TILE_FRAME:02X}\n")

    # --- step-0 PRG banking proof: a signature byte in each data bank -------
    with open(GEN / "testbanks.s", "w") as f:
        f.write("; GENERATED by tools/build.py - PRG bank signature bytes\n")
        for b in range(24):
            f.write(f'.segment "BANK{b:02d}"\n')
            f.write(f"    .byte ${b ^ 0x5A:02X}\n")

    print(f"CHR image: {n} bytes ({n//1024} banks)")


if __name__ == "__main__":
    build()
