"""CHR (pattern table) helpers: 8x8 tile art -> 2bpp planar NES tiles.

Art is authored as a list of 8 strings of 8 characters each. The character set
maps to the 4 colour indices of a sub-palette:

    '.' or ' '  = 0 (transparent / backdrop)
    '1'         = 1
    '2'         = 2
    '3'         = 3

Anything else raises, so typos in art are caught at build time.
"""

BANK_TILES = 64          # tiles in a 1KB CHR bank
BANK_BYTES = 1024

_COLMAP = {'.': 0, ' ': 0, '0': 0, '1': 1, '2': 2, '3': 3}


def tile_from_rows(rows):
    """rows: 8 strings of 8 chars -> 16-byte 2bpp planar tile."""
    if len(rows) != 8:
        raise ValueError(f"tile needs 8 rows, got {len(rows)}")
    lo, hi = [], []
    for r in rows:
        if len(r) != 8:
            raise ValueError(f"tile row must be 8 chars, got {len(r)!r}")
        l = h = 0
        for c in r:
            v = _COLMAP.get(c)
            if v is None:
                raise ValueError(f"bad art char {c!r} in row {r!r}")
            l = (l << 1) | (v & 1)
            h = (h << 1) | ((v >> 1) & 1)
        lo.append(l)
        hi.append(h)
    return bytes(lo + hi)


BLANK_TILE = bytes(16)


def grid_to_tiles(grid, w, h):
    """Cut a w*8 by h*8 character grid into tiles, row-major.

    grid: list of h*8 strings, each w*8 chars.
    Returns a list of w*h 16-byte tiles ordered left-to-right, top-to-bottom.
    """
    if len(grid) != h * 8:
        raise ValueError(f"grid needs {h*8} rows, got {len(grid)}")
    for r in grid:
        if len(r) != w * 8:
            raise ValueError(f"grid row must be {w*8} chars, got {len(r)}")
    out = []
    for ty in range(h):
        for tx in range(w):
            rows = [grid[ty * 8 + y][tx * 8:tx * 8 + 8] for y in range(8)]
            out.append(tile_from_rows(rows))
    return out


class ChrRom:
    """A 128KB CHR-ROM laid out as 128 banks of 1KB (64 tiles each)."""

    def __init__(self, n_banks=128):
        self.n_banks = n_banks
        self.banks = [[BLANK_TILE] * BANK_TILES for _ in range(n_banks)]
        self.used = [False] * n_banks
        self.labels = {}

    def put_bank(self, index, tiles, label=""):
        """Place up to 64 tiles into 1KB bank `index`."""
        if len(tiles) > BANK_TILES:
            raise ValueError(
                f"bank {index} ({label}): {len(tiles)} tiles > {BANK_TILES}")
        if self.used[index]:
            raise ValueError(f"CHR bank {index} already used by {self.labels[index]}")
        b = list(tiles) + [BLANK_TILE] * (BANK_TILES - len(tiles))
        self.banks[index] = b
        self.used[index] = True
        self.labels[index] = label
        return index

    def put_span(self, start, tiles, label=""):
        """Place tiles across consecutive 1KB banks starting at `start`."""
        n = (len(tiles) + BANK_TILES - 1) // BANK_TILES
        for i in range(n):
            self.put_bank(start + i, tiles[i * BANK_TILES:(i + 1) * BANK_TILES],
                          f"{label}#{i}")
        return start

    def to_bytes(self):
        out = bytearray()
        for b in self.banks:
            for t in b:
                out += t
        return bytes(out)


def emit_chr_asm(chr_rom, path):
    data = chr_rom.to_bytes()
    with open(path, "w") as f:
        f.write("; GENERATED by tools/build.py - CHR-ROM image\n")
        f.write('.segment "CHARS"\n')
        for i in range(0, len(data), 16):
            f.write(".byte " + ",".join(f"${b:02X}" for b in data[i:i + 16]) + "\n")
    return len(data)


def emit_bytes(f, name, data, per_line=16):
    if name:
        f.write(f"{name}:\n")
    for i in range(0, len(data), per_line):
        f.write("    .byte " + ",".join(f"${b:02X}" for b in data[i:i + per_line]) + "\n")
