#!/usr/bin/env python3
"""Generate game/nes.cfg — the ld65 config for THRENOS.

ROM: MMC3 (mapper 4), 256KB PRG (32 x 8KB banks), 128KB CHR (128 x 1KB banks),
8KB battery-backed PRG-RAM at $6000.

PRG bank map
------------
  banks  0..23  DATA banks, linked at $8000 (MMC3 register R6 window)
  banks 24..29  CODE banks, linked at $A000 (MMC3 register R7 window)
  bank  30      FIXED, $C000-$DFFF  (engine: field, text, menus, battle core)
  bank  31      FIXED, $E000-$FFFF  (kernel: reset, NMI, banking, vectors)

RAM map
-------
  $0000-$00FF  zeropage
  $0100-$01FF  stack
  $0200-$02FF  shadow OAM (DMA page)
  $0300-$03FF  VRAM buffer / NMI transfer staging
  $0400-$07FF  game RAM (BSS)
  $6000-$67FF  save data (battery; checksummed)
  $6800-$7FFF  work RAM (battery-backed but volatile in meaning: WRAM segment)
"""
import pathlib

N_DATA = 24          # banks 0..23  @ $8000
N_CODE = 6           # banks 24..29 @ $A000
N_PRG_BANKS = 32

out = []
out.append("# GENERATED by tools/gen_cfg.py — do not edit by hand.\n")
out.append("MEMORY {\n")
out.append("    ZP:      start=$0000, size=$0100, type=rw, define=yes;\n")
out.append("    OAM:     start=$0200, size=$0100, type=rw, define=yes;\n")
out.append("    VBUF:    start=$0300, size=$0100, type=rw, define=yes;\n")
out.append("    RAM:     start=$0400, size=$0400, type=rw, define=yes;\n")
out.append("    SAVE:    start=$6000, size=$0800, type=rw, define=yes;\n")
out.append("    WORK:    start=$6800, size=$1800, type=rw, define=yes;\n")
out.append("\n")
out.append("    HDR:     start=$0000, size=$0010, type=ro, file=%O, fill=yes;\n")
for i in range(N_DATA):
    out.append(f"    PB{i:02d}:    start=$8000, size=$2000, type=ro, file=%O, fill=yes, fillval=$FF;\n")
for i in range(N_DATA, N_DATA + N_CODE):
    out.append(f"    PB{i:02d}:    start=$A000, size=$2000, type=ro, file=%O, fill=yes, fillval=$FF;\n")
out.append("    PB30:    start=$C000, size=$2000, type=ro, file=%O, fill=yes, fillval=$FF;\n")
out.append("    PB31:    start=$E000, size=$2000, type=ro, file=%O, fill=yes, fillval=$FF;\n")
out.append("    CHR:     start=$0000, size=$20000, type=ro, file=%O, fill=yes, fillval=$00;\n")
out.append("}\n\n")

out.append("SEGMENTS {\n")
out.append("    HEADER:   load=HDR,  type=ro;\n")
for i in range(N_PRG_BANKS - 2):
    out.append(f"    BANK{i:02d}:   load=PB{i:02d}, type=ro, optional=yes;\n")
out.append("    ENGINE:   load=PB30, type=ro;\n")
out.append("    ENGRO:    load=PB30, type=ro, optional=yes;\n")
out.append("    KERNEL:   load=PB31, type=ro;\n")
out.append("    KERNRO:   load=PB31, type=ro, optional=yes;\n")
out.append("    VECTORS:  load=PB31, type=ro, start=$FFFA;\n")
out.append("    CHARS:    load=CHR,  type=ro;\n")
out.append("\n")
out.append("    ZEROPAGE: load=ZP,   type=zp;\n")
out.append("    OAMBUF:   load=OAM,  type=bss, align=$100, optional=yes;\n")
out.append("    VBUFSEG:  load=VBUF, type=bss, optional=yes;\n")
out.append("    BSS:      load=RAM,  type=bss, optional=yes;\n")
out.append("    SAVEDAT:  load=SAVE, type=bss, optional=yes;\n")
out.append("    WRAM:     load=WORK, type=bss, optional=yes;\n")
out.append("}\n")

p = pathlib.Path(__file__).resolve().parent.parent / "nes.cfg"
p.write_text("".join(out))
print(f"wrote {p}")
