; sound.s — THRENOS sound driver. PRG bank 24 ($A000 code window).
;
; Pattern-based, 4 channels (pulse 1, pulse 2, triangle, noise; no DMC).
; SoundTick is called from NMI every frame including lag frames. It touches
; only the APU, the zero-page bytes snd_bank/snd_tmp, and the state page
; snd_state ($6E00-$6EFF). All music data lives in this bank, so the tick never
; switches banks.
;
; The main thread never calls in directly: it writes a byte to music_req /
; sfx_req and SoundTick consumes it ($00 = nothing pending, $FF = silence).
;
; =============================================================================
; ON-ROM DATA FORMAT  (generated by tools/music.py -> src/gen/music.s)
; =============================================================================
;
; song_tab: .addr per song id (entry 0 unused: id 0 means "no request").
; sfx_tab:  .addr per sfx id  (entry 0 unused).
;
; SONG HEADER
;   +0  tempo        frames per row (row = 1/16 note; 1..255)
;   +1  n_order      number of order rows
;   +2  loop_n       order rows from the loop point to the end
;                    ($00 = one-shot: the song stops at the end)
;   +3  loop_ptr     .addr of the order row to jump back to
;   +5  order        n_order rows of 8 bytes:
;                       .addr pat_ch0, pat_ch1, pat_ch2, pat_ch3
;                    (channel order: pulse1, pulse2, triangle, noise)
;
; PATTERN — a two-byte header and then an event stream. The header makes every
; pattern self-contained, so patterns are freely shared between songs (the
; compiler dedups them) without costing two stream events at every boundary.
;   +0 inst     the instrument this pattern starts on
;   +1 len      the note length this pattern starts on, in rows
;   +2..        the event stream:
;   $00        END        end of pattern -> pull the next one from the order
;   $01..$60   NOTE n     key on, pitch index n (1..96), lasts `len` rows
;   $61        REST       key off, lasts `len` rows
;   $62 pp     SLUR pp    change pitch to pp without retriggering (used when a
;                         note straddles a pattern boundary)
;   $63 ii     INST ii    select instrument ii (0..15)
;   $64..$FF   LEN        set note length = code - $63 rows (1..156)
;
; Pitch index 1..96 maps to MIDI note 33..128 (A1..G#8) through pitch_lo/
; pitch_hi (128 entries, so arpeggio offsets can run off the top safely).
; Triangle notes are pre-transposed +12 by the compiler, because the triangle
; sounds an octave below a pulse for the same timer value. On the noise channel
; the pitch index is 1..16 = noise period 0..15.
;
; INSTRUMENT (16 max) — five parallel 16-byte tables:
;   inst_env[i]   start offset into env_data
;   inst_duty[i]  pulse duty in bits 6-7 (noise: bit7 = mode flag), else 0
;   inst_vib[i]   $00 = no vibrato; else phase increment per frame (1..15)
;   inst_vibd[i]  which of the four 16-entry vib_tab shapes to use ($00/$10/
;                 $20/$30) — the depth is baked into the table
;   inst_arp[i]   $00 = none; else semitone offsets for arp steps 1 and 2
;                 packed as two nibbles (high = step 1, low = step 2)
;
; ENVELOPE (env_data) — one byte per frame at 60Hz:
;   $00..$0F   volume, then advance
;   $80|v      volume v, hold here forever (sustain; every envelope ends in one)
;
; SFX
;   +0  channel*4 (0, 4, 8 or 12)
;   +1  steps of 4 bytes: frames, $4000+c byte, $4002+c byte, $4003+c byte
;       frames = 0 ends the sfx. While an sfx runs the music does not write that
;       channel; when it ends the music channel is re-keyed.
;
; =============================================================================

.include "nes.inc"
.include "zp.inc"
.include "ram.inc"
.include "banks.inc"

.export SoundInit, SoundTick, SoundPlay, SoundSfx

.import song_tab, sfx_tab
.import inst_env, inst_duty, inst_vib, inst_vibd, inst_arp
.import env_data, pitch_lo, pitch_hi

; -----------------------------------------------------------------------------
; State — all of it inside snd_state ($6E00-$6EFF).
;
; The per-channel arrays are indexed by channel*4 (0,4,8,12) so that the same X
; also indexes the APU: $4000,x / $4002,x / $4003,x are the right registers for
; every channel. Stride 4 wastes 12 bytes per array and buys ~20 cycles a frame.
; -----------------------------------------------------------------------------
ch_ptrl   = snd_state+$00       ; pattern stream pointer
ch_ptrh   = snd_state+$10
ch_dur    = snd_state+$20       ; rows left in the current note
ch_len    = snd_state+$30       ; current default note length, in rows
ch_inst   = snd_state+$40
ch_note   = snd_state+$50       ; current pitch index (0 = key off)
ch_env    = snd_state+$60       ; current index into env_data
ch_vibp   = snd_state+$70       ; vibrato phase
ch_hi     = snd_state+$80       ; last timer-high byte written
ch_ordl   = snd_state+$90       ; pointer to the channel's next order row
ch_ordh   = snd_state+$A0
ch_cnt    = snd_state+$B0       ; order rows left before the loop point
ch_flag   = snd_state+$C0       ; bit7 active, bit6 steady, bit0 key-on
ch_arpp   = snd_state+$D0       ; arpeggio phase (0..2)

snd_song  = snd_state+$E0       ; playing song id ($FF = none)
snd_tempo = snd_state+$E1
snd_rowt  = snd_state+$E2       ; frames until the next row
snd_loopn = snd_state+$E3
snd_loopl = snd_state+$E4
snd_looph = snd_state+$E5
snd_vol   = snd_state+$E6       ; scratch: this channel's volume this frame
snd_lo    = snd_state+$E7       ; scratch: timer low
snd_hi    = snd_state+$E8       ; scratch: timer high
sfx_ch    = snd_state+$E9       ; channel*4 of the running sfx ($FF = none)
sfx_ptl   = snd_state+$EA
sfx_pth   = snd_state+$EB
sfx_tim   = snd_state+$EC       ; frames left in the current sfx step
snd_t0    = snd_state+$ED       ; scratch
snd_t1    = snd_state+$EE
snd_stc   = snd_state+$F0       ; 2: self-test frame counter (test builds only)

FLAG_ACTIVE = %10000000
FLAG_STEADY = %01000000         ; nothing can change before the next row: skip
FLAG_KEYON  = %00000001
NOT_STEADY  = %10111111
NOT_KEYON   = %11111110

.segment "BANK24"

; -----------------------------------------------------------------------------
; SoundInit — silence the APU and clear all driver state.
; -----------------------------------------------------------------------------
.proc SoundInit
    lda #$00
    tax
@clr:
    sta snd_state,x
    inx
    bne @clr

    lda #$FF
    sta snd_song
    sta sfx_ch

    lda #$0F
    sta APUSTATUS           ; pulse 1/2, triangle, noise on; DMC off
    lda #$30                ; constant volume 0, length counter halted
    sta APUPULSE1
    sta APUPULSE2
    sta APUNOISE
    lda #$08                ; sweep disabled
    sta APUPULSE1+1
    sta APUPULSE2+1
    lda #$80                ; triangle linear counter = 0 -> silent
    sta APUTRI
    rts
.endproc

; -----------------------------------------------------------------------------
; SoundTick — one frame. Called from NMI, every frame.
; -----------------------------------------------------------------------------
.proc SoundTick
.ifdef SOUND_SELFTEST
    jsr SelfTest
.endif
    lda music_req
    beq @nomus
    ldy #0
    sty music_req
    jsr SoundPlay
@nomus:
    lda sfx_req
    beq @nosfx
    ldy #0
    sty sfx_req
    jsr SoundSfx
@nosfx:
    lda snd_song
    bmi @nosong

    dec snd_rowt
    bne @nofetch
    lda snd_tempo
    sta snd_rowt
    ldx #0
    jsr RowAdvance
    ldx #4
    jsr RowAdvance
    ldx #8
    jsr RowAdvance
    ldx #12
    jsr RowAdvance
@nofetch:
    ldx #0
    jsr ChanFrame
    ldx #4
    jsr ChanFrame
    ldx #8
    jsr ChanFrame
    ldx #12
    jsr ChanFrame
@nosong:
    jmp SfxFrame
.endproc

; -----------------------------------------------------------------------------
; SoundPlay — A = song id. $00 or $FF stops the music.
; -----------------------------------------------------------------------------
.proc SoundPlay
    cmp #$FF
    beq @stop
    cmp #$00
    bne :+
@stop:
    jmp Stop
:   sta snd_song
    asl a
    tay
    lda song_tab,y
    sta snd_tmp
    lda song_tab+1,y
    sta snd_tmp+1

    ldy #0
    lda (snd_tmp),y         ; tempo
    sta snd_tempo
    iny
    lda (snd_tmp),y         ; order length
    sta snd_bank
    iny
    lda (snd_tmp),y         ; loop length
    sta snd_loopn
    iny
    lda (snd_tmp),y
    sta snd_loopl
    iny
    lda (snd_tmp),y
    sta snd_looph

    lda snd_tmp             ; order base = header + 5
    clc
    adc #5
    sta snd_t0
    lda snd_tmp+1
    adc #0
    sta snd_t1

    lda #1
    sta snd_rowt

    ldx #12
@init:
    lda snd_t0
    sta ch_ordl,x
    lda snd_t1
    sta ch_ordh,x
    lda snd_bank
    sta ch_cnt,x
    lda #<pat_empty         ; an END byte: the first row pulls from the order
    sta ch_ptrl,x
    lda #>pat_empty
    sta ch_ptrh,x
    lda #1
    sta ch_dur,x            ; ...on the very next row tick
    lda #4
    sta ch_len,x
    lda #0
    sta ch_note,x
    sta ch_inst,x
    sta ch_env,x
    sta ch_vibp,x
    sta ch_arpp,x
    sta ch_hi,x
    lda #FLAG_ACTIVE
    sta ch_flag,x
    jsr MuteChan
    dex
    dex
    dex
    dex
    bpl @init
    rts
.endproc

; Stop everything (kept next to SoundPlay so `beq Stop` stays in range).
.proc Stop
    lda #$FF
    sta snd_song
    ldx #12
@l:
    lda #0
    sta ch_flag,x
    sta ch_note,x
    jsr MuteChan
    dex
    dex
    dex
    dex
    bpl @l
    rts
.endproc

pat_empty:
    .byte $00

; -----------------------------------------------------------------------------
; MuteChan — X = channel*4.
; -----------------------------------------------------------------------------
.proc MuteChan
    cpx #8
    beq @tri
    lda #$30
    sta $4000,x
    rts
@tri:
    lda #$80
    sta APUTRI
    rts
.endproc

; -----------------------------------------------------------------------------
; RowAdvance — X = channel*4. Called once per row; parses the next event(s).
; -----------------------------------------------------------------------------
.proc RowAdvance
    lda ch_flag,x
    bpl @rts
    dec ch_dur,x
    beq @next
@rts:
    rts

@next:
    lda ch_ptrl,x
    sta snd_tmp
    lda ch_ptrh,x
    sta snd_tmp+1
    ldy #0
@ev:
    lda (snd_tmp),y
    iny
    beq @end                ; $00
    cmp #$61
    bcc @note               ; $01..$60
    beq @rest               ; $61
    cmp #$63
    bcc @slur               ; $62
    beq @inst               ; $63
    sec                     ; $64..$FF: set note length
    sbc #$63
    sta ch_len,x
    jmp @ev

@inst:
    lda (snd_tmp),y
    iny
    sta ch_inst,x
    jmp @ev

@slur:
    lda (snd_tmp),y
    iny
    sta ch_note,x
    lda #FLAG_ACTIVE        ; clears steady, no retrigger
    sta ch_flag,x
    jmp @dur

@rest:
    lda #0
    sta ch_note,x
    lda #FLAG_ACTIVE
    sta ch_flag,x
    jmp @dur

@note:
    sta ch_note,x
    sty snd_bank            ; save the stream offset
    ldy ch_inst,x
    lda inst_env,y
    sta ch_env,x
    lda #0
    sta ch_vibp,x
    lda #(FLAG_ACTIVE|FLAG_KEYON)
    sta ch_flag,x
    ldy snd_bank

@dur:
    lda ch_len,x
    sta ch_dur,x
    tya                     ; write the stream pointer back
    clc
    adc snd_tmp
    sta ch_ptrl,x
    lda snd_tmp+1
    adc #0
    sta ch_ptrh,x
    rts

; End of pattern: take the next one from this channel's order pointer.
@end:
    lda ch_cnt,x
    bne @take
    lda snd_loopn
    beq @stop               ; one-shot song: this channel is done
    sta ch_cnt,x
    lda snd_loopl
    sta ch_ordl,x
    lda snd_looph
    sta ch_ordh,x
@take:
    dec ch_cnt,x
    lda ch_ordl,x
    sta snd_tmp
    clc
    adc #8                  ; an order row is 8 bytes
    sta ch_ordl,x
    lda ch_ordh,x
    sta snd_tmp+1
    adc #0
    sta ch_ordh,x
    txa                     ; this channel's entry is at offset ch*2 = X/2
    lsr a
    tay
    lda (snd_tmp),y
    sta snd_bank
    iny
    lda (snd_tmp),y
    sta snd_tmp+1
    lda snd_bank
    sta snd_tmp
    ldy #0                  ; the pattern header: starting instrument, length
    lda (snd_tmp),y
    sta ch_inst,x
    iny
    lda (snd_tmp),y
    sta ch_len,x
    iny
    jmp @ev

@stop:
    lda #0
    sta ch_flag,x
    sta ch_note,x
    jmp MuteChan
.endproc

; -----------------------------------------------------------------------------
; ChanFrame — X = channel*4. Per-frame envelope, modulation and APU writes.
;
; snd_bank is used as the "went steady" marker: it starts at 1 and is cleared by
; anything that can still change the sound next frame (a moving envelope,
; vibrato, arpeggio). A steady channel is skipped entirely until the next note.
; -----------------------------------------------------------------------------
.proc ChanFrame
    lda ch_flag,x
    bpl @skip               ; channel not active
    and #FLAG_STEADY
    bne @skip               ; nothing can have changed since last frame
    cpx sfx_ch
    bne @go                 ; an sfx owns this channel
@skip:
    rts
@go:
    lda ch_note,x
    bne :+
    jmp @mute
:   lda #1
    sta snd_bank

    ; --- volume envelope -----------------------------------------------------
    ldy ch_env,x
    lda env_data,y
    bmi @esus
    inc ch_env,x
    lda #0
    sta snd_bank            ; envelope still moving
    lda env_data,y
@esus:
    and #$0F
    sta snd_vol

    ; --- is the pitch going to move this frame? ------------------------------
    ; If the instrument has neither vibrato nor arpeggio and this is not the
    ; frame the note started, the timer registers already hold the right value
    ; and only the volume needs rewriting. That is the common case.
    ldy ch_inst,x
    lda inst_arp,y
    ora inst_vib,y
    bne @modul
    lda ch_flag,x
    lsr a                   ; key-on -> carry
    bcs @modul

    cpx #8
    beq @tvol
    bcs @nvol
    lda inst_duty,y
    ora #$30
    ora snd_vol
    sta $4000,x
    jmp @finish
@nvol:
    lda #$30
    ora snd_vol
    sta $4000,x
    jmp @finish
@tvol:
    lda #$80
    ldy snd_vol
    beq :+
    lda #$FF
:   sta $4000,x
    jmp @finish

    ; --- arpeggio ------------------------------------------------------------
@modul:
    lda inst_arp,y
    beq @noarp
    sta snd_t0
    lda #0
    sta snd_bank
    ldy ch_arpp,x
    iny
    cpy #3
    bcc :+
    ldy #0
:   tya
    sta ch_arpp,x
    beq @noarp
    lda snd_t0
    cpy #1
    bne :+
    lsr a
    lsr a
    lsr a
    lsr a
:   and #$0F
    clc
    adc ch_note,x
    jmp @pitch
@noarp:
    lda ch_note,x

@pitch:
    cpx #12
    bne :+
    jmp @noise
:   tay
    lda pitch_lo,y
    sta snd_lo
    lda pitch_hi,y
    sta snd_hi

    ; --- vibrato -------------------------------------------------------------
    ldy ch_inst,x
    lda inst_vib,y          ; phase increment (0 = no vibrato)
    beq @novib
    lda #0
    sta snd_bank
    lda inst_vib,y
    clc
    adc ch_vibp,x
    sta ch_vibp,x
    lsr a
    lsr a
    lsr a
    lsr a                   ; phase step 0..15
    ora inst_vibd,y         ; + this instrument's depth table
    tay
    lda vib_tab,y           ; signed delta
    tay
    clc
    adc snd_lo
    sta snd_lo
    tya
    bmi @vneg
    lda snd_hi
    adc #0
    sta snd_hi
    jmp @novib
@vneg:
    lda snd_hi
    adc #$FF
    sta snd_hi
@novib:

    ; --- write the channel ---------------------------------------------------
    cpx #8
    beq @tri
    ldy ch_inst,x
    lda inst_duty,y
    ora #$30
    ora snd_vol
    sta $4000,x
    jmp @wrpitch

@tri:
    lda snd_vol
    beq @trioff
    lda #$FF                ; linear counter max, control flag set
    sta $4000,x
    jmp @wrpitch
@trioff:
    lda #$80
    sta $4000,x
    jmp @finish

@wrpitch:
    lda snd_lo
    sta $4002,x
    lda snd_hi
    cmp ch_hi,x
    bne @wrhi
    lda ch_flag,x
    lsr a                   ; key-on -> carry
    bcc @finish
    lda snd_hi
@wrhi:
    sta ch_hi,x
    sta $4003,x
    jmp @finish

@noise:
    sec                     ; pitch index 1..16 -> noise period 0..15
    sbc #1
    and #$0F
    ldy ch_inst,x
    ora inst_duty,y         ; bit7 = short-mode flag
    sta $4002,x
    lda #$30
    ora snd_vol
    sta $4000,x
    lda ch_flag,x
    lsr a
    bcc @finish
    lda #$08
    sta $4003,x             ; retrigger

@finish:
    lda ch_flag,x
    and #NOT_KEYON
    ldy snd_bank
    beq :+
    ora #FLAG_STEADY
:   sta ch_flag,x
    rts

@mute:
    jsr MuteChan
    lda ch_flag,x
    ora #FLAG_STEADY
    and #NOT_KEYON
    sta ch_flag,x
    rts
.endproc

; Vibrato shapes: one cycle of a signed triangle at four depths. The high nibble
; of the index picks the depth (inst_vibd), the low nibble is the phase.
vib_tab:
    .byte  0,  1,  2,  3,  3,  3,  2,  1
    .byte  0, $FF,$FE,$FD,$FD,$FD,$FE,$FF
    .byte  0,  2,  4,  6,  6,  6,  4,  2
    .byte  0, $FE,$FC,$FA,$FA,$FA,$FC,$FE
    .byte  0,  3,  6,  9,  9,  9,  6,  3
    .byte  0, $FD,$FA,$F7,$F7,$F7,$FA,$FD
    .byte  0,  5, 10, 15, 15, 15, 10,  5
    .byte  0, $FB,$F6,$F1,$F1,$F1,$F6,$FB

; -----------------------------------------------------------------------------
; SoundSfx — A = sfx id. $00/$FF cancels whatever is playing.
; -----------------------------------------------------------------------------
.proc SoundSfx
    cmp #$FF
    beq @cancel
    cmp #$00
    beq @cancel
    asl a
    tay
    lda sfx_tab,y
    sta snd_tmp
    lda sfx_tab+1,y
    sta snd_tmp+1
    ldy #0
    lda (snd_tmp),y         ; channel*4
    sta sfx_ch
    lda snd_tmp
    clc
    adc #1
    sta sfx_ptl
    lda snd_tmp+1
    adc #0
    sta sfx_pth
    lda #1
    sta sfx_tim             ; SfxFrame loads step 0 later this same frame
    rts
@cancel:
    ldx sfx_ch
    bmi @rts
    jmp SfxDone
@rts:
    rts
.endproc

; -----------------------------------------------------------------------------
; SfxFrame — advance the running sfx, if any.
; -----------------------------------------------------------------------------
.proc SfxFrame
    ldx sfx_ch
    bmi @rts
    dec sfx_tim
    bne @rts
    lda sfx_ptl
    sta snd_tmp
    lda sfx_pth
    sta snd_tmp+1
    ldy #0
    lda (snd_tmp),y         ; frames in this step
    beq SfxDone
    sta sfx_tim
    iny
    lda (snd_tmp),y
    sta $4000,x
    iny
    lda (snd_tmp),y
    sta $4002,x
    iny
    lda (snd_tmp),y
    sta $4003,x
    lda sfx_ptl
    clc
    adc #4
    sta sfx_ptl
    bcc @rts
    inc sfx_pth
@rts:
    rts
.endproc

; Hand the channel back to the music (X = channel*4).
.proc SfxDone
    lda #$FF
    sta sfx_ch
    lda ch_flag,x
    and #NOT_STEADY
    ora #FLAG_KEYON
    sta ch_flag,x
    bmi @rts                ; a song still owns it: it re-keys next frame
    jmp MuteChan
@rts:
    rts
.endproc

; -----------------------------------------------------------------------------
; Self-test hook — test builds only (ca65 -D SOUND_SELFTEST).
;
; The game engine that will write music_req/sfx_req is being built in parallel,
; so test/t_sound.py links a ROM with this hook: it drives the driver through
; every song and every sfx from the inside, using exactly the same request-byte
; interface the engine will use. It is not in the shipping ROM.
; -----------------------------------------------------------------------------
.ifdef SOUND_SELFTEST
.include "gen/songids.inc"
.proc SelfTest
    inc snd_stc
    bne :+
    inc snd_stc+1
:   lda snd_stc
    bne @sfx
    lda snd_stc+1           ; a new song every 256 frames
    and #$07
    tay
    iny
    cpy #(N_SONGS+1)
    bcc :+
    ldy #1
:   sty music_req
    rts
@sfx:
    and #$3F                ; an sfx every 64 frames
    bne @rts
    lda snd_stc
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    and #$03
    tay
    iny
    cpy #(N_SFX+1)
    bcc :+
    ldy #1
:   sty sfx_req
@rts:
    rts
.endproc
.endif
