#!/usr/bin/env python3
"""Dev-time asset generator for the vertical slice.

Source-of-truth for the CHR tiles, the one-screen field map, and the text
window tilemap. NOT part of the `make` build: it emits committed .s files
(src/chr.s, src/field.s) that ca65 assembles. Re-run by hand after editing art,
then commit the generated .s.

Tiles are 8x8, pixel values 0-3 selecting a color within the active palette.
The attribute table is palette-aware: water -> palette 1, NPC -> palette 2,
everything else -> palette 0. The text window region is switched to palette 3
at runtime.
"""

import os

# ---------------------------------------------------------------------------
# Background tile indices (pattern table 0)
#
# A background character (the NPC) gets four facings, each a 2x2 block:
#   down/up/left/right. Background tiles can't be hardware-flipped, so the
#   "left" facing is generated by mirroring the authored "side" (right) art.
# ---------------------------------------------------------------------------
T_BLANK, T_GRASS, T_FLOWER, T_PATH, T_TREE, T_WALL, T_BUSH, T_WATER = range(8)
NPC_DOWN, NPC_UP, NPC_LEFT, NPC_RIGHT = 0x08, 0x0C, 0x10, 0x14   # 4 tiles each
W_TL, W_T, W_TR, W_L, W_FILL, W_R, W_BL, W_B, W_BR = range(0x18, 0x21)
F_BASE = 0x21          # font glyph tiles ($21 onward); enemy tiles follow them

# Sprite tile indices (pattern table 1). A sprite character gets three authored
# facings; "left" is the side art with the OAM horizontal-flip bit set at draw
# time, so only down/up/side need tiles.
HERO_DOWN, HERO_UP, HERO_SIDE = 0x00, 0x04, 0x08   # 4 tiles each

NPC_FACE = {"down": NPC_DOWN, "up": NPC_UP, "left": NPC_LEFT, "right": NPC_RIGHT}

WATER = T_WATER

# ---------------------------------------------------------------------------
# Field tile art. '0'-'3' = color index within the tile's palette.
# ---------------------------------------------------------------------------
TILES = {
    T_BLANK: ["00000000"] * 8,
    T_GRASS: [
        "11112111", "11111111", "21111121", "11111111",
        "11211111", "11111111", "11111121", "21111111",
    ],
    T_FLOWER: [
        "11111111", "11122111", "11233211", "11232311",
        "11233211", "11122111", "11111111", "11111111",
    ],
    T_PATH: [
        "33333333", "33133333", "33333313", "33333333",
        "31333333", "33333133", "33333333", "33313333",
    ],
    T_TREE: [
        "12222221", "22222222", "22322322", "22222222",
        "22322322", "22222222", "12333321", "11333311",
    ],
    T_WALL: [
        "33333333", "33333333", "13131313", "33333333",
        "33333333", "31313131", "33333333", "33333333",
    ],
    T_BUSH: [
        "11111111", "11222211", "12222221", "12222221",
        "12222221", "11222211", "11111111", "11111111",
    ],
    T_WATER: [
        "11111111", "12211221", "11111111", "21122112",
        "11111111", "12211221", "11111111", "21122112",
    ],
}

# ---------------------------------------------------------------------------
# Hero metasprite: 16x16, drawn as a 2x2 block of tiles in pattern table 1.
# Three authored facings (down/up/side); "left" is the side art H-flipped at
# draw time. Value 0 = transparent. Sprite palette 0: 1=red, 2=tan, 3=white.
# ---------------------------------------------------------------------------
HERO_VIEWS = {
    "down": [
        "0000011111100000",
        "0000122222210000",
        "0001222222221000",
        "0001223223221000",   # two eyes
        "0001222222221000",
        "0001222222221000",
        "0000122222210000",
        "0000011111100000",
        "0001111111111000",
        "0011111111111100",
        "0011111111111100",
        "0011111111111100",
        "0001111111111000",
        "0001100000011000",
        "0001100000011000",
        "0001100000011000",
    ],
    "up": [   # back of the head: no face
        "0000011111100000",
        "0000122222210000",
        "0001222222221000",
        "0001222222221000",
        "0001222222221000",
        "0001222222221000",
        "0000122222210000",
        "0000011111100000",
        "0001111111111000",
        "0011111111111100",
        "0011111111111100",
        "0011111111111100",
        "0001111111111000",
        "0001100000011000",
        "0001100000011000",
        "0001100000011000",
    ],
    "side": [   # profile, facing RIGHT: one eye and a nose on the right
        "0000111111000000",
        "0001222222100000",
        "0012222222210000",
        "0012222223210000",   # eye toward the right
        "0012222222232000",   # nose bump
        "0012222222210000",
        "0001222222100000",
        "0000111111000000",
        "0001111111100000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0001111111100000",
        "0001110011000000",
        "0001110011000000",
        "0001110011000000",
    ],
}

# ---------------------------------------------------------------------------
# NPC: 16x16 drawn as BACKGROUND tiles (palette 2). Value 0 renders as the
# universal backdrop ($0F black) so it reads as an outline. Same three authored
# facings; "left" is mirrored from "side" by the tool (BG can't flip).
# 1=robe, 2=skin, 3=eyes/white.
# ---------------------------------------------------------------------------
NPC_VIEWS = {
    "down": [
        "0000111111100000",
        "0001122222110000",
        "0011222222211000",
        "0011233223211000",   # two eyes
        "0011222222211000",
        "0011222222211000",
        "0001122222110000",
        "0011111111110000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0011111111110000",
        "0001111111100000",
    ],
    "up": [   # back of the hood: no face
        "0000111111100000",
        "0001122222110000",
        "0011222222211000",
        "0011222222211000",
        "0011222222211000",
        "0011222222211000",
        "0001122222110000",
        "0011111111110000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0011111111110000",
        "0001111111100000",
    ],
    "side": [   # profile robe, facing RIGHT
        "0000111111000000",
        "0001222222100000",
        "0012222222100000",
        "0012222232100000",   # eye toward the right
        "0012222222320000",   # nose bump
        "0012222222100000",
        "0001222222100000",
        "0001111111100000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0001111111100000",
        "0000111111000000",
    ],
}

# Which way the (stationary) demo NPC faces. Any of down/up/left/right.
NPC_FACING = "down"

# ---------------------------------------------------------------------------
# Text window (Dragon-Warrior style): black box, white double-line border and
# white text. Palette 3 is color0 = black (the universal backdrop $0F),
# color1 = white ($30). So glyphs/frame are '#' = white ink (value 1) on
# '.' = black (value 0). 5x7 cell, baseline on row 6, descenders on row 7.
# ---------------------------------------------------------------------------
ARROW = "\x1f"    # the "more text" prompt glyph (down triangle)
CURSOR = "\x10"   # menu cursor glyph (right triangle)

FONT = {
    " ": ["........"] * 8,
    ARROW: ["........", "........", "#######.", ".#####..",
            "..###...", "...#....", "........", "........"],
    CURSOR: ["........", ".#......", ".##.....", ".###....",
             ".####...", ".###....", ".##.....", ".#......"],
    # lowercase
    "a": ["........", "........", ".###....", "....#...", ".####...", "#...#...", ".####...", "........"],
    "b": ["#.......", "#.......", "#.##....", "##..#...", "#...#...", "#...#...", "##.#....", "........"],
    "c": ["........", "........", ".###....", "#...#...", "#.......", "#...#...", ".###....", "........"],
    "d": ["....#...", "....#...", ".##.#...", "#..##...", "#...#...", "#...#...", ".##.#...", "........"],
    "e": ["........", "........", ".###....", "#...#...", "#####...", "#.......", ".###....", "........"],
    "f": ["..##....", ".#..#...", ".#......", "###.....", ".#......", ".#......", ".#......", "........"],
    "g": ["........", "........", ".##.#...", "#..#....", "#..#....", ".###....", "...#....", ".##....."],
    "h": ["#.......", "#.......", "#.##....", "##..#...", "#...#...", "#...#...", "#...#...", "........"],
    "i": ["..#.....", "........", ".##.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "j": ["...#....", "........", "..##....", "...#....", "...#....", "#..#....", ".##.....", "........"],
    "k": ["#.......", "#.......", "#..#....", "#.#.....", "##......", "#.#.....", "#..#....", "........"],
    "l": [".##.....", "..#.....", "..#.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "m": ["........", "........", "########", "##.##.##", "##.##.##", "##.##.##", "##.##.##", "........"],
    "n": ["........", "........", "#.##....", "##..#...", "#...#...", "#...#...", "#...#...", "........"],
    "o": ["........", "........", ".###....", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "p": ["........", "........", "#.##....", "##..#...", "#...#...", "##.#....", "#.......", "#......."],
    "q": ["........", "........", ".##.#...", "#..##...", "#...#...", ".##.#...", "....#...", "....#..."],
    "r": ["........", "........", "#.##....", "##..#...", "#.......", "#.......", "#.......", "........"],
    "s": ["........", "........", ".####...", "#.......", ".###....", "....#...", "####....", "........"],
    "t": [".#......", ".#......", "###.....", ".#......", ".#......", ".#..#...", "..##....", "........"],
    "u": ["........", "........", "#...#...", "#...#...", "#...#...", "#..##...", ".##.#...", "........"],
    "v": ["........", "........", "#...#...", "#...#...", "#...#...", ".#.#....", "..#.....", "........"],
    "w": ["........", "........", "##.##.##", "##.##.##", "##.##.##", "##.##.##", "########", "........"],
    "x": ["........", "........", "#...#...", ".#.#....", "..#.....", ".#.#....", "#...#...", "........"],
    "y": ["........", "........", "#...#...", "#...#...", "#..##...", ".##.#...", "....#...", ".###...."],
    "z": ["........", "........", "#####...", "...#....", "..#.....", ".#......", "#####...", "........"],
    # uppercase
    "A": ["........", ".###....", "#...#...", "#...#...", "#####...", "#...#...", "#...#...", "........"],
    "B": ["........", "####....", "#...#...", "####....", "#...#...", "#...#...", "####....", "........"],
    "C": ["........", ".###....", "#...#...", "#.......", "#.......", "#...#...", ".###....", "........"],
    "D": ["........", "###.....", "#..#....", "#...#...", "#...#...", "#..#....", "###.....", "........"],
    "E": ["........", "#####...", "#.......", "###.....", "#.......", "#.......", "#####...", "........"],
    "F": ["........", "#####...", "#.......", "###.....", "#.......", "#.......", "#.......", "........"],
    "G": ["........", ".###....", "#...#...", "#.......", "#.##....", "#...#...", ".###....", "........"],
    "H": ["........", "#...#...", "#...#...", "#####...", "#...#...", "#...#...", "#...#...", "........"],
    "I": ["........", ".###....", "..#.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "J": ["........", "..###...", "...#....", "...#....", "...#....", "#..#....", ".##.....", "........"],
    "K": ["........", "#...#...", "#..#....", "###.....", "#.#.....", "#..#....", "#...#...", "........"],
    "L": ["........", "#.......", "#.......", "#.......", "#.......", "#.......", "#####...", "........"],
    "M": ["........", "##....##", "###..###", "##.##.##", "##....##", "##....##", "##....##", "........"],
    "N": ["........", "#...#...", "##..#...", "#.#.#...", "#..##...", "#...#...", "#...#...", "........"],
    "O": ["........", ".###....", "#...#...", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "P": ["........", "####....", "#...#...", "#...#...", "####....", "#.......", "#.......", "........"],
    "Q": ["........", ".###....", "#...#...", "#...#...", "#.#.#...", "#..#....", ".##.#...", "........"],
    "R": ["........", "####....", "#...#...", "#...#...", "####....", "#.#.....", "#..#....", "........"],
    "S": ["........", ".####...", "#.......", ".###....", "....#...", "....#...", "####....", "........"],
    "T": ["........", "#####...", "..#.....", "..#.....", "..#.....", "..#.....", "..#.....", "........"],
    "U": ["........", "#...#...", "#...#...", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "V": ["........", "#...#...", "#...#...", "#...#...", "#...#...", ".#.#....", "..#.....", "........"],
    "W": ["........", "##....##", "##....##", "##....##", "##.##.##", "###..###", "##....##", "........"],
    "X": ["........", "#...#...", ".#.#....", "..#.....", "..#.....", ".#.#....", "#...#...", "........"],
    "Y": ["........", "#...#...", "#...#...", ".#.#....", "..#.....", "..#.....", "..#.....", "........"],
    "Z": ["........", "#####...", "...#....", "..#.....", ".#......", "#.......", "#####...", "........"],
    # digits
    "0": ["........", ".###....", "#...#...", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "1": ["........", "..#.....", ".##.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "2": ["........", ".###....", "#...#...", "...#....", "..#.....", ".#......", "#####...", "........"],
    "3": ["........", "####....", "....#...", "..##....", "....#...", "#...#...", ".###....", "........"],
    "4": ["........", "...##...", "..#.#...", ".#..#...", "#####...", "....#...", "....#...", "........"],
    "5": ["........", "#####...", "#.......", "####....", "....#...", "#...#...", ".###....", "........"],
    "6": ["........", "..##....", ".#......", "####....", "#...#...", "#...#...", ".###....", "........"],
    "7": ["........", "#####...", "....#...", "...#....", "..#.....", ".#......", ".#......", "........"],
    "8": ["........", ".###....", "#...#...", ".###....", "#...#...", "#...#...", ".###....", "........"],
    "9": ["........", ".###....", "#...#...", "#...#...", ".####...", "....#...", ".##.....", "........"],
    # punctuation
    ":": ["........", "........", ".##.....", ".##.....", "........", ".##.....", ".##.....", "........"],
    ".": ["........", "........", "........", "........", "........", ".##.....", ".##.....", "........"],
    ",": ["........", "........", "........", "........", "........", ".##.....", ".##.....", ".#......"],
    "'": [".#......", ".#......", ".#......", "........", "........", "........", "........", "........"],
    "!": ["..#.....", "..#.....", "..#.....", "..#.....", "..#.....", "........", "..#.....", "........"],
    "?": [".###....", "#...#...", "...#....", "..#.....", "..#.....", "........", "..#.....", "........"],
    "-": ["........", "........", "........", ".###....", "........", "........", "........", "........"],
}

# ---------------------------------------------------------------------------
# Messages. Authored as plain strings; the tool word-wraps to the interior
# width and paginates to 4 lines, emitting a byte stream the runtime renders:
#   tile bytes (glyph or $00 space) ... per line, with control codes
#   $FE = newline, $FD = page break (wait for A), $FF = end of message.
# Pages are padded to exactly 4 lines so a new page fully overwrites the last.
# ---------------------------------------------------------------------------
MSG_NEWLINE, MSG_PAGE, MSG_END = 0xFE, 0xFD, 0xFF
TEXT_W, TEXT_H = 30, 4   # interior width / lines per page

MESSAGES = [
    # name, text
    # "\f" forces a page break (press A to advance to the next page).
    ("NPC_GREETING",
     "Hi you!\f"
     "Welcome to the world!"),
    ("SLIME_APPEARS", "A Slime draws near!"),
    ("SLIME_DEFEATED", "The Slime is defeated!"),
    ("NOBODY", "There is no one there."),
]

# Fragments composed with a runtime number into a one-line battle message:
#   <DMG_PRE><number><DMG_POST>  e.g. "The Slime takes 6 damage!"
# Emitted as $FF-terminated tile streams the runtime concatenates.
FRAGMENTS = [
    ("DMG_PRE", "The Slime takes "),
    ("DMG_POST", " damage!"),
    # menu labels
    ("OPT_TALK", "Talk"),
    ("OPT_EQUIP", "Equip"),
    ("WPN0", "Club"),
    ("WPN1", "Sword"),
    ("LBL_ATK", "  ATK "),
    ("LBL_POWER", "Power: "),
]

# ---------------------------------------------------------------------------
# Enemy: authored at 16x16, doubled to 32x32, drawn as background tiles on the
# battle screen (battle palette 1). Value 0 = transparent -> the blue battle
# backdrop shows through, so the blob's silhouette blends cleanly.
#   1 = body, 2 = shading, 3 = eyes/mouth (white).
# ---------------------------------------------------------------------------
ENEMY16 = [
    "0000001111000000",
    "0000011111100000",
    "0000111111110000",
    "0001111111111000",
    "0011111111111100",
    "0011311113111100",
    "0111311113111110",
    "0111111111111110",
    "1111111111111111",
    "1111111111111111",
    "1111122221111111",
    "1111111111111111",
    "0111111111111110",
    "0011111111111100",
    "0000111111110000",
    "0000000000000000",
]

# Where the NPC stands, in 16px grid cells (must match NPC_GX/GY in main.s).
NPC_GX, NPC_GY = 6, 6


def to_chr(rows):
    """Encode one 8x8 tile (rows of digit chars) to 16 planar bytes."""
    p0, p1 = [], []
    for row in rows:
        b0 = b1 = 0
        for px in row:
            v = int(px)
            b0 = (b0 << 1) | (v & 1)
            b1 = (b1 << 1) | ((v >> 1) & 1)
        p0.append(b0)
        p1.append(b1)
    return p0 + p1


def split16(block):
    """Split a 16x16 art block into 4 8x8 tiles ordered TL, TR, BL, BR."""
    return [
        [r[0:8] for r in block[0:8]],
        [r[8:16] for r in block[0:8]],
        [r[0:8] for r in block[8:16]],
        [r[8:16] for r in block[8:16]],
    ]


def mirror_h(block):
    """Horizontally mirror an art block (used to make a left-facing BG view)."""
    return [row[::-1] for row in block]


def mirror_v(block):
    """Vertically mirror an art block."""
    return block[::-1]


def double(block):
    """2x-scale an NxN art block (each pixel becomes 2x2)."""
    out = []
    for row in block:
        big = "".join(c * 2 for c in row)
        out.append(big)
        out.append(big)
    return out


def split_grid(block, n):
    """Split an (8n)x(8n) art block into n*n 8x8 tiles, row-major."""
    tiles = []
    for tr in range(n):
        for tc in range(n):
            tiles.append([r[tc * 8:(tc + 1) * 8] for r in block[tr * 8:(tr + 1) * 8]])
    return tiles


# Dragon-Warrior-style frame: black box with a white double line near the edge,
# rounded corners. '#' = white (value 1), '.' = black (value 0). Only the
# top-left corner and the top/left edges are authored; the rest are mirrored.
WIN_TL_ART = [
    "........",
    "........",
    "..######",
    "..#.....",
    "..#.####",
    "..#.#...",
    "..#.#...",
    "..#.#...",
]
WIN_T_ART = [
    "........",
    "........",
    "########",
    "........",
    "########",
    "........",
    "........",
    "........",
]
WIN_L_ART = [
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
]
WIN_FILL_ART = ["........"] * 8


def to_digits(art):
    """Convert '#'/'.' art into the digit strings to_chr() expects (1=white)."""
    return ["".join("1" if c == "#" else "0" for c in row) for row in art]


# Glyphs that already have 1px-gap vertical strokes (combs); right-dilation
# would blob them, so they are authored pre-thickened and skip the pass.
BOLD_EXEMPT = set("mwMW")


def thicken(art):
    """Faux-bold: extend each stroke one pixel to the right (2px stems)."""
    out = []
    for row in art:
        new = list(row)
        for j in range(1, len(row)):
            if row[j] == "." and row[j - 1] == "#":
                new[j] = "#"
        out.append("".join(new))
    return out


def glyph(ch):
    """Font tile: '#' = white ink (value 1) on '.' = black (value 0)."""
    art = FONT[ch]
    if ch not in BOLD_EXEMPT:
        art = thicken(art)
    return to_digits(art)


def wrap_text(text, width):
    """Greedy word-wrap into a list of lines no wider than `width`."""
    lines, cur = [], ""
    for word in text.split():
        assert len(word) <= width, f"word too long: {word!r}"
        if not cur:
            cur = word
        elif len(cur) + 1 + len(word) <= width:
            cur += " " + word
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines


def encode_message(text, font_id):
    """Wrap + paginate `text` into the runtime byte stream (see MESSAGES).
    A form-feed ("\\f") in the source forces a page break."""
    pages = []
    for segment in text.split("\f"):
        lines = wrap_text(segment, TEXT_W)
        for p in range(0, max(len(lines), 1), TEXT_H):
            pages.append(lines[p:p + TEXT_H])

    out = []
    for pi, page in enumerate(pages):
        page = list(page) + [""] * (TEXT_H - len(page))   # pad to 4 lines
        last_page = pi == len(pages) - 1
        for i, line in enumerate(page):
            for ch in line:
                out.append(0x00 if ch == " " else font_id[ch])
            if i < TEXT_H - 1:
                out.append(MSG_NEWLINE)
            else:
                out.append(MSG_END if last_page else MSG_PAGE)
    return out


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(here, "src")

    # --- assemble the ordered background tile table (16x16 metatiles) ---
    # Terrain is authored as 8x8 art, pixel-doubled to 16x16 and split into the
    # four CHR subtiles (TL,TR,BL,BR) of one metatile. The hero and NPC are
    # already 16x16. Window/font/enemy tiles stay 8x8 (used by the text box).
    bg = {0: TILES[T_BLANK]}        # tile $00 = blank (palette-independent)
    nid = 1

    TERRAIN = [T_GRASS, T_FLOWER, T_PATH, T_TREE, T_WALL, T_BUSH, T_WATER]
    meta_terrain = {}
    for t in TERRAIN:
        ids = []
        for sub in split16(double(TILES[t])):
            bg[nid] = sub
            ids.append(nid)
            nid += 1
        meta_terrain[t] = ids

    # NPC metatile: the one authored facing it stands in (left = mirrored side).
    if NPC_FACING == "left":
        npc_block = mirror_h(NPC_VIEWS["side"])
    elif NPC_FACING == "right":
        npc_block = NPC_VIEWS["side"]
    else:
        npc_block = NPC_VIEWS[NPC_FACING]
    npc_ids = []
    for sub in split16(npc_block):
        bg[nid] = sub
        npc_ids.append(nid)
        nid += 1

    # Window frame (8x8): author TL + top/left edges + fill; mirror the rest.
    tl = to_digits(WIN_TL_ART)
    top = to_digits(WIN_T_ART)
    left = to_digits(WIN_L_ART)
    win_art = [("TL", tl), ("T", top), ("TR", mirror_h(tl)),
               ("L", left), ("FILL", to_digits(WIN_FILL_ART)), ("R", mirror_h(left)),
               ("BL", mirror_v(tl)), ("B", mirror_v(top)), ("BR", mirror_v(mirror_h(tl)))]
    W_ids = {}
    for name, art in win_art:
        bg[nid] = art
        W_ids[name] = nid
        nid += 1

    # Font glyphs.
    font_chars = sorted(FONT.keys())
    font_id = {}
    for ch in font_chars:
        bg[nid] = glyph(ch)
        font_id[ch] = nid
        nid += 1

    # Enemy (32x32 = 4x4 tiles).
    e_base = nid
    for tile in split_grid(double(ENEMY16), 4):
        bg[nid] = tile
        nid += 1

    last_bg = nid - 1
    bg_bytes = []
    for tid in range(last_bg + 1):
        bg_bytes += to_chr(bg.get(tid, ["00000000"] * 8))

    # Hero sprite tiles: down, up, side (left = side H-flipped at draw time).
    hero_bytes = []
    for view in ("down", "up", "side"):
        for tile in split16(HERO_VIEWS[view]):
            hero_bytes += to_chr(tile)

    with open(os.path.join(src, "chr.s"), "w") as f:
        f.write("; chr.s - GENERATED by tools/gen_assets.py. Do not edit by hand.\n")
        f.write("; Pattern table 0: field tiles, NPC (4 facings), window, font, enemy ($00-$%02X).\n" % last_bg)
        f.write("; Pattern table 1 ($1000): hero tiles - down $00, up $04, side $08.\n")
        f.write("; The CHR region fills the remaining 8KB with zero (see nes.cfg).\n\n")
        f.write('.segment "CHARS"\n')
        f.write("    ; --- pattern table 0: background ---\n")
        for i in range(0, len(bg_bytes), 16):
            row = ", ".join(f"${b:02X}" for b in bg_bytes[i:i + 16])
            f.write(f"    .byte {row}   ; bg tile ${i // 16:02X}\n")
        pad = 0x1000 - len(bg_bytes)
        f.write(f"\n    .res ${pad:04X}, $00   ; pad to pattern table 1 ($1000)\n\n")
        f.write("    ; --- pattern table 1: sprites ---\n")
        for i in range(0, len(hero_bytes), 16):
            row = ", ".join(f"${b:02X}" for b in hero_bytes[i:i + 16])
            f.write(f"    .byte {row}   ; hero tile ${i // 16:02X}\n")

    # --- build the metatile world: 32 x 30 metatiles = 2 x 2 screens
    # (512 x 480 px). The world wraps on both axes (a torus). Horizontal fits
    # in the two side-by-side nametables; vertical is row-streamed at runtime.
    WM, HM = 32, 30
    world = [[T_GRASS] * WM for _ in range(HM)]
    # ponds
    for y in range(2, 5):
        for x in range(3, 7):
            world[y][x] = T_WATER
    for y in range(20, 24):
        for x in range(24, 29):
            world[y][x] = T_WATER
    # roads: vertical seams + two horizontal roads (one per screen-row band)
    for y in range(HM):
        world[y][15] = T_PATH
    for x in range(WM):
        world[7][x] = T_PATH
        world[22][x] = T_PATH
    for y in range(HM):
        world[y][3] = T_PATH
    # a walled hut (top-right screen) with a doorway
    for x in range(20, 25):
        world[3][x] = T_WALL
        world[6][x] = T_WALL
    for y in range(3, 7):
        world[y][20] = T_WALL
        world[y][24] = T_WALL
    world[6][22] = T_PATH
    # tree clusters across the world
    for (x, y) in [(8, 1), (9, 1), (8, 2), (27, 13), (28, 13), (28, 12),
                   (6, 17), (7, 17), (6, 18), (18, 26), (19, 26), (19, 27),
                   (11, 24), (12, 24)]:
        world[y][x] = T_TREE
    for (x, y) in [(9, 10), (26, 11), (12, 4), (6, 10), (20, 16), (29, 19),
                   (5, 25), (14, 19), (22, 28), (10, 14), (27, 25)]:
        world[y][x] = T_FLOWER
    for (x, y) in [(11, 2), (29, 8), (2, 6), (18, 12), (25, 9), (13, 18),
                   (8, 28), (21, 20), (30, 27), (4, 14)]:
        world[y][x] = T_BUSH

    SOLID = {T_TREE, T_WALL, T_WATER}

    def cell_ids(mx, my):
        if (mx, my) == (NPC_GX, NPC_GY):
            return npc_ids
        return meta_terrain[world[my][mx]]

    def cell_pal(mx, my):
        if (mx, my) == (NPC_GX, NPC_GY):
            return 2
        return 1 if world[my][mx] == T_WATER else 0

    # worldtiles: the whole world as 8px tiles, 60 tile-rows x 64 tile-cols,
    # row-major. Within each tile-row the first 32 cols are the LEFT nametable
    # ($2000, metatile cols 0..15) and the next 32 are the RIGHT ($2400, cols
    # 16..31). The runtime streams one tile-row strip at a time from here.
    worldtiles = [0] * (60 * 64)
    for my in range(HM):
        for mx in range(WM):
            t0, t1, t2, t3 = cell_ids(mx, my)
            col = (0 if mx < 16 else 32) + (mx % 16) * 2
            r0 = (my * 2) * 64
            r1 = (my * 2 + 1) * 64
            worldtiles[r0 + col] = t0
            worldtiles[r0 + col + 1] = t1
            worldtiles[r1 + col] = t2
            worldtiles[r1 + col + 1] = t3

    # Attribute palette-pairs, per metatile-row, per attribute column. One
    # metatile == one attribute quadrant, so an attr byte combines two metatile
    # rows (even row -> low nibble, odd row -> high nibble). For each metatile
    # row we precompute, per attr column (0..7), the pair
    #   pal(left metatile) | pal(right metatile) << 2   (a 4-bit nibble),
    # separately for the left and right nametables. The runtime read-modify-
    # writes its attribute shadow with these by row parity.
    def attr_pairs(base):
        rows = []
        for my in range(HM):
            row = []
            for c in range(8):
                p0 = cell_pal(base + 2 * c, my)
                p1 = cell_pal(base + 2 * c + 1, my)
                row.append(p0 | (p1 << 2))
            rows.append(row)
        return rows
    pair_l = attr_pairs(0)     # left nametable, metatile cols 0..15
    pair_r = attr_pairs(16)    # right nametable, metatile cols 16..31
    attr_pair_l = [pair_l[my][c] for my in range(HM) for c in range(8)]
    attr_pair_r = [pair_r[my][c] for my in range(HM) for c in range(8)]

    # Per-metatile collision map (1 = solid), indexed [my*WM + mx].
    worldsolid = []
    for my in range(HM):
        for mx in range(WM):
            solid = world[my][mx] in SOLID or (mx, my) == (NPC_GX, NPC_GY)
            worldsolid.append(1 if solid else 0)

    # Per-metatile palette (0/1/2), indexed [my*WM + mx]. Used to rebuild the
    # attribute table for the current view when a menu/dialog box opens.
    worldpal = [cell_pal(mx, my) for my in range(HM) for mx in range(WM)]

    # --- build the window SHELL: frame + blank interior, 32 wide x 8 tall ---
    # (used by the gated text box; unchanged from the previous milestone)
    IN_W = 30
    pad_row = [W_ids["L"]] + [W_ids["FILL"]] * IN_W + [W_ids["R"]]
    winmap = [W_ids["TL"]] + [W_ids["T"]] * IN_W + [W_ids["TR"]]
    winmap += pad_row
    winmap += pad_row * 4
    winmap += pad_row
    winmap += [W_ids["BL"]] + [W_ids["B"]] * IN_W + [W_ids["BR"]]
    win_steps = 9

    with open(os.path.join(src, "field.s"), "w") as f:
        f.write("; field.s - GENERATED by tools/gen_assets.py. Do not edit by hand.\n")
        f.write("; 2x2 scrolling world (32x30 metatiles). worldtiles is the whole world\n")
        f.write("; as 8px tiles (60 rows x 64 cols: [32 left | 32 right] per row); the\n")
        f.write("; runtime fills the two nametables from it and streams rows on scroll.\n")
        f.write("; attr_pair_l/r feed the attribute shadow; worldsolid is collision.\n\n")
        f.write(".export worldtiles, attr_pair_l, attr_pair_r, worldsolid, worldpal, winmap\n\n")
        f.write('.segment "RODATA"\n')
        f.write(fmt_bytes("worldtiles", worldtiles, 32) + "\n\n")
        f.write(fmt_bytes("attr_pair_l", attr_pair_l, 8) + "\n\n")
        f.write(fmt_bytes("attr_pair_r", attr_pair_r, 8) + "\n\n")
        f.write(fmt_bytes("worldsolid", worldsolid, 32) + "\n\n")
        f.write(fmt_bytes("worldpal", worldpal, 32) + "\n\n")
        f.write(fmt_bytes("winmap", winmap, 32) + "\n")

    # --- messages + fragments ---
    encoded = [(name, encode_message(text, font_id)) for name, text in MESSAGES]
    frags = [(name, [0x00 if c == " " else font_id[c] for c in text] + [0xFF])
             for name, text in FRAGMENTS]
    with open(os.path.join(src, "messages.s"), "w") as f:
        f.write("; messages.s - GENERATED by tools/gen_assets.py. Do not edit by hand.\n")
        f.write("; msg_table: word pointers indexed by MSG_* (see tiles.inc).\n")
        f.write("; frag_*: $FF-terminated tile streams for runtime composition.\n\n")
        f.write(".export msg_table")
        for name, _ in frags:
            f.write(f", frag_{name}")
        f.write("\n\n")
        f.write('.segment "RODATA"\n')
        f.write("msg_table:\n")
        for name, _ in encoded:
            f.write(f"    .word msg_{name}\n")
        f.write("\n")

        def emit_bytes(label, data):
            f.write(f"{label}:\n")
            for i in range(0, len(data), 16):
                row = ", ".join(f"${b:02X}" for b in data[i:i + 16])
                f.write(f"    .byte {row}\n")
            f.write("\n")

        for name, data in encoded:
            emit_bytes("msg_" + name, data)
        for name, data in frags:
            emit_bytes("frag_" + name, data)

    # tile-index constants consumed by main.s (so nothing is hardcoded there)
    with open(os.path.join(src, "tiles.inc"), "w") as f:
        f.write("; tiles.inc - GENERATED by tools/gen_assets.py. Do not edit by hand.\n\n")
        f.write("; Sprite tiles (pattern table 1), 4 tiles per facing.\n")
        f.write(f"HERO_DOWN_TILE = ${HERO_DOWN:02X}\n")
        f.write(f"HERO_UP_TILE   = ${HERO_UP:02X}\n")
        f.write(f"HERO_SIDE_TILE = ${HERO_SIDE:02X}\n\n")
        f.write("; Background tiles (pattern table 0).\n")
        f.write(f"ENEMY_TILE_BASE = ${e_base:02X}\n")
        f.write(f"ARROW_TILE = ${font_id[ARROW]:02X}   ; 'more text' prompt\n")
        f.write(f"WIN_BOTTOM_TILE = ${W_ids['B']:02X}   ; bottom-border tile (restores under the prompt)\n")
        f.write(f"DIGIT_TILE = ${font_id['0']:02X}   ; '0'; digit d -> DIGIT_TILE + d\n")
        f.write(f"CURSOR_TILE = ${font_id[CURSOR]:02X}   ; menu cursor (right triangle)\n\n")
        f.write("; World geometry (16px metatiles): 2 screens wide, 1 tall.\n")
        f.write(f"WORLD_W = {WM}\n")
        f.write(f"WORLD_H = {HM}\n")
        f.write("; Text window: full-width box at nametable rows 20-27.\n")
        f.write(f"WIN_STEPS = {win_steps}\n")
        f.write(f"TEXT_COLS = {TEXT_W}\n")
        f.write(f"TEXT_LINES = {TEXT_H}\n")
        f.write("; Message control codes and ids.\n")
        f.write(f"MSG_NEWLINE = ${MSG_NEWLINE:02X}\n")
        f.write(f"MSG_PAGE    = ${MSG_PAGE:02X}\n")
        f.write(f"MSG_END     = ${MSG_END:02X}\n")
        for i, (name, _) in enumerate(MESSAGES):
            f.write(f"MSG_{name} = {i}\n")

    # console preview (| marks the screen seam at metatile col 16)
    glyphs = {T_GRASS: ".", T_FLOWER: ",", T_PATH: ":", T_TREE: "T",
              T_WALL: "#", T_BUSH: "o", T_WATER: "~"}
    print("World preview, %dx%d metatiles (N = NPC, facing %s):" % (WM, HM, NPC_FACING))
    for y in range(HM):
        line = ""
        for x in range(WM):
            if x == 16:
                line += "|"
            line += "N" if (x, y) == (NPC_GX, NPC_GY) else glyphs.get(world[y][x], "?")
        print(line)


def fmt_bytes(label, data, per_line):
    out = [f"{label}:"]
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"${b:02X}" for b in data[i:i + per_line])
        out.append(f"    .byte {chunk}")
    return "\n".join(out)


if __name__ == "__main__":
    main()
