#!/usr/bin/env python3
"""Dev-time asset generator for the vertical slice.

Source-of-truth for the CHR tiles, the one-screen field map, and the text
window tilemap. NOT part of the `make` build: it emits committed .s files
(src/chr.s, src/field.s) that ca65 assembles. Re-run by hand after editing art,
then commit the generated .s.

Tiles are 8x8, pixel values 0-3 selecting a color within the active palette.
The attribute table is palette-aware: water -> palette 1, NPC -> palette 2,
everything else -> palette 0. The text window region is switched to palette 3
at runtime.
"""

import os

# ---------------------------------------------------------------------------
# Background tile indices (pattern table 0)
#
# A background character (the NPC) gets four facings, each a 2x2 block:
#   down/up/left/right. Background tiles can't be hardware-flipped, so the
#   "left" facing is generated by mirroring the authored "side" (right) art.
# ---------------------------------------------------------------------------
T_BLANK, T_GRASS, T_FLOWER, T_PATH, T_TREE, T_WALL, T_BUSH, T_WATER = range(8)
NPC_DOWN, NPC_UP, NPC_LEFT, NPC_RIGHT = 0x08, 0x0C, 0x10, 0x14   # 4 tiles each
W_TL, W_T, W_TR, W_L, W_FILL, W_R, W_BL, W_B, W_BR = range(0x18, 0x21)
F_BASE = 0x21          # font glyph tiles ($21 onward); enemy tiles follow them

# Sprite tile indices (pattern table 1). A sprite character gets three authored
# facings; "left" is the side art with the OAM horizontal-flip bit set at draw
# time, so only down/up/side need tiles.
HERO_DOWN, HERO_UP, HERO_SIDE = 0x00, 0x04, 0x08   # 4 tiles each

NPC_FACE = {"down": NPC_DOWN, "up": NPC_UP, "left": NPC_LEFT, "right": NPC_RIGHT}

WATER = T_WATER

# ---------------------------------------------------------------------------
# Field tile art. '0'-'3' = color index within the tile's palette.
# ---------------------------------------------------------------------------
TILES = {
    T_BLANK: ["00000000"] * 8,
    T_GRASS: [
        "11112111", "11111111", "21111121", "11111111",
        "11211111", "11111111", "11111121", "21111111",
    ],
    T_FLOWER: [
        "11111111", "11122111", "11233211", "11232311",
        "11233211", "11122111", "11111111", "11111111",
    ],
    T_PATH: [
        "33333333", "33133333", "33333313", "33333333",
        "31333333", "33333133", "33333333", "33313333",
    ],
    T_TREE: [
        "12222221", "22222222", "22322322", "22222222",
        "22322322", "22222222", "12333321", "11333311",
    ],
    T_WALL: [
        "33333333", "33333333", "13131313", "33333333",
        "33333333", "31313131", "33333333", "33333333",
    ],
    T_BUSH: [
        "11111111", "11222211", "12222221", "12222221",
        "12222221", "11222211", "11111111", "11111111",
    ],
    T_WATER: [
        "11111111", "12211221", "11111111", "21122112",
        "11111111", "12211221", "11111111", "21122112",
    ],
}

# ---------------------------------------------------------------------------
# Hero metasprite: 16x16, drawn as a 2x2 block of tiles in pattern table 1.
# Three authored facings (down/up/side); "left" is the side art H-flipped at
# draw time. Value 0 = transparent. Sprite palette 0: 1=red, 2=tan, 3=white.
# ---------------------------------------------------------------------------
HERO_VIEWS = {
    "down": [
        "0000011111100000",
        "0000122222210000",
        "0001222222221000",
        "0001223223221000",   # two eyes
        "0001222222221000",
        "0001222222221000",
        "0000122222210000",
        "0000011111100000",
        "0001111111111000",
        "0011111111111100",
        "0011111111111100",
        "0011111111111100",
        "0001111111111000",
        "0001100000011000",
        "0001100000011000",
        "0001100000011000",
    ],
    "up": [   # back of the head: no face
        "0000011111100000",
        "0000122222210000",
        "0001222222221000",
        "0001222222221000",
        "0001222222221000",
        "0001222222221000",
        "0000122222210000",
        "0000011111100000",
        "0001111111111000",
        "0011111111111100",
        "0011111111111100",
        "0011111111111100",
        "0001111111111000",
        "0001100000011000",
        "0001100000011000",
        "0001100000011000",
    ],
    "side": [   # profile, facing RIGHT: one eye and a nose on the right
        "0000111111000000",
        "0001222222100000",
        "0012222222210000",
        "0012222223210000",   # eye toward the right
        "0012222222232000",   # nose bump
        "0012222222210000",
        "0001222222100000",
        "0000111111000000",
        "0001111111100000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0001111111100000",
        "0001110011000000",
        "0001110011000000",
        "0001110011000000",
    ],
}

# ---------------------------------------------------------------------------
# NPC: 16x16 drawn as BACKGROUND tiles (palette 2). Value 0 renders as the
# universal backdrop ($0F black) so it reads as an outline. Same three authored
# facings; "left" is mirrored from "side" by the tool (BG can't flip).
# 1=robe, 2=skin, 3=eyes/white.
# ---------------------------------------------------------------------------
NPC_VIEWS = {
    "down": [
        "0000111111100000",
        "0001122222110000",
        "0011222222211000",
        "0011233223211000",   # two eyes
        "0011222222211000",
        "0011222222211000",
        "0001122222110000",
        "0011111111110000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0011111111110000",
        "0001111111100000",
    ],
    "up": [   # back of the hood: no face
        "0000111111100000",
        "0001122222110000",
        "0011222222211000",
        "0011222222211000",
        "0011222222211000",
        "0011222222211000",
        "0001122222110000",
        "0011111111110000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0111111111111000",
        "0011111111110000",
        "0001111111100000",
    ],
    "side": [   # profile robe, facing RIGHT
        "0000111111000000",
        "0001222222100000",
        "0012222222100000",
        "0012222232100000",   # eye toward the right
        "0012222222320000",   # nose bump
        "0012222222100000",
        "0001222222100000",
        "0001111111100000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0011111111110000",
        "0001111111100000",
        "0000111111000000",
    ],
}

# Which way the (stationary) demo NPC faces. Any of down/up/left/right.
NPC_FACING = "down"

# ---------------------------------------------------------------------------
# Text window (Dragon-Warrior style): black box, white double-line border and
# white text. Palette 3 is color0 = black (the universal backdrop $0F),
# color1 = white ($30). So glyphs/frame are '#' = white ink (value 1) on
# '.' = black (value 0). 5x7 cell, baseline on row 6, descenders on row 7.
# ---------------------------------------------------------------------------
ARROW = "\x1f"    # the "more text" prompt glyph (down triangle)
CURSOR = "\x10"   # menu cursor glyph (right triangle)

FONT = {
    " ": ["........"] * 8,
    ARROW: ["........", "........", "#######.", ".#####..",
            "..###...", "...#....", "........", "........"],
    CURSOR: ["........", ".#......", ".##.....", ".###....",
             ".####...", ".###....", ".##.....", ".#......"],
    # lowercase
    "a": ["........", "........", ".###....", "....#...", ".####...", "#...#...", ".####...", "........"],
    "b": ["#.......", "#.......", "#.##....", "##..#...", "#...#...", "#...#...", "##.#....", "........"],
    "c": ["........", "........", ".###....", "#...#...", "#.......", "#...#...", ".###....", "........"],
    "d": ["....#...", "....#...", ".##.#...", "#..##...", "#...#...", "#...#...", ".##.#...", "........"],
    "e": ["........", "........", ".###....", "#...#...", "#####...", "#.......", ".###....", "........"],
    "f": ["..##....", ".#..#...", ".#......", "###.....", ".#......", ".#......", ".#......", "........"],
    "g": ["........", "........", ".##.#...", "#..#....", "#..#....", ".###....", "...#....", ".##....."],
    "h": ["#.......", "#.......", "#.##....", "##..#...", "#...#...", "#...#...", "#...#...", "........"],
    "i": ["..#.....", "........", ".##.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "j": ["...#....", "........", "..##....", "...#....", "...#....", "#..#....", ".##.....", "........"],
    "k": ["#.......", "#.......", "#..#....", "#.#.....", "##......", "#.#.....", "#..#....", "........"],
    "l": [".##.....", "..#.....", "..#.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "m": ["........", "........", "########", "##.##.##", "##.##.##", "##.##.##", "##.##.##", "........"],
    "n": ["........", "........", "#.##....", "##..#...", "#...#...", "#...#...", "#...#...", "........"],
    "o": ["........", "........", ".###....", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "p": ["........", "........", "#.##....", "##..#...", "#...#...", "##.#....", "#.......", "#......."],
    "q": ["........", "........", ".##.#...", "#..##...", "#...#...", ".##.#...", "....#...", "....#..."],
    "r": ["........", "........", "#.##....", "##..#...", "#.......", "#.......", "#.......", "........"],
    "s": ["........", "........", ".####...", "#.......", ".###....", "....#...", "####....", "........"],
    "t": [".#......", ".#......", "###.....", ".#......", ".#......", ".#..#...", "..##....", "........"],
    "u": ["........", "........", "#...#...", "#...#...", "#...#...", "#..##...", ".##.#...", "........"],
    "v": ["........", "........", "#...#...", "#...#...", "#...#...", ".#.#....", "..#.....", "........"],
    "w": ["........", "........", "##.##.##", "##.##.##", "##.##.##", "##.##.##", "########", "........"],
    "x": ["........", "........", "#...#...", ".#.#....", "..#.....", ".#.#....", "#...#...", "........"],
    "y": ["........", "........", "#...#...", "#...#...", "#..##...", ".##.#...", "....#...", ".###...."],
    "z": ["........", "........", "#####...", "...#....", "..#.....", ".#......", "#####...", "........"],
    # uppercase
    "A": ["........", ".###....", "#...#...", "#...#...", "#####...", "#...#...", "#...#...", "........"],
    "B": ["........", "####....", "#...#...", "####....", "#...#...", "#...#...", "####....", "........"],
    "C": ["........", ".###....", "#...#...", "#.......", "#.......", "#...#...", ".###....", "........"],
    "D": ["........", "###.....", "#..#....", "#...#...", "#...#...", "#..#....", "###.....", "........"],
    "E": ["........", "#####...", "#.......", "###.....", "#.......", "#.......", "#####...", "........"],
    "F": ["........", "#####...", "#.......", "###.....", "#.......", "#.......", "#.......", "........"],
    "G": ["........", ".###....", "#...#...", "#.......", "#.##....", "#...#...", ".###....", "........"],
    "H": ["........", "#...#...", "#...#...", "#####...", "#...#...", "#...#...", "#...#...", "........"],
    "I": ["........", ".###....", "..#.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "J": ["........", "..###...", "...#....", "...#....", "...#....", "#..#....", ".##.....", "........"],
    "K": ["........", "#...#...", "#..#....", "###.....", "#.#.....", "#..#....", "#...#...", "........"],
    "L": ["........", "#.......", "#.......", "#.......", "#.......", "#.......", "#####...", "........"],
    "M": ["........", "##....##", "###..###", "##.##.##", "##....##", "##....##", "##....##", "........"],
    "N": ["........", "#...#...", "##..#...", "#.#.#...", "#..##...", "#...#...", "#...#...", "........"],
    "O": ["........", ".###....", "#...#...", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "P": ["........", "####....", "#...#...", "#...#...", "####....", "#.......", "#.......", "........"],
    "Q": ["........", ".###....", "#...#...", "#...#...", "#.#.#...", "#..#....", ".##.#...", "........"],
    "R": ["........", "####....", "#...#...", "#...#...", "####....", "#.#.....", "#..#....", "........"],
    "S": ["........", ".####...", "#.......", ".###....", "....#...", "....#...", "####....", "........"],
    "T": ["........", "#####...", "..#.....", "..#.....", "..#.....", "..#.....", "..#.....", "........"],
    "U": ["........", "#...#...", "#...#...", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "V": ["........", "#...#...", "#...#...", "#...#...", "#...#...", ".#.#....", "..#.....", "........"],
    "W": ["........", "##....##", "##....##", "##....##", "##.##.##", "###..###", "##....##", "........"],
    "X": ["........", "#...#...", ".#.#....", "..#.....", "..#.....", ".#.#....", "#...#...", "........"],
    "Y": ["........", "#...#...", "#...#...", ".#.#....", "..#.....", "..#.....", "..#.....", "........"],
    "Z": ["........", "#####...", "...#....", "..#.....", ".#......", "#.......", "#####...", "........"],
    # digits
    "0": ["........", ".###....", "#...#...", "#...#...", "#...#...", "#...#...", ".###....", "........"],
    "1": ["........", "..#.....", ".##.....", "..#.....", "..#.....", "..#.....", ".###....", "........"],
    "2": ["........", ".###....", "#...#...", "...#....", "..#.....", ".#......", "#####...", "........"],
    "3": ["........", "####....", "....#...", "..##....", "....#...", "#...#...", ".###....", "........"],
    "4": ["........", "...##...", "..#.#...", ".#..#...", "#####...", "....#...", "....#...", "........"],
    "5": ["........", "#####...", "#.......", "####....", "....#...", "#...#...", ".###....", "........"],
    "6": ["........", "..##....", ".#......", "####....", "#...#...", "#...#...", ".###....", "........"],
    "7": ["........", "#####...", "....#...", "...#....", "..#.....", ".#......", ".#......", "........"],
    "8": ["........", ".###....", "#...#...", ".###....", "#...#...", "#...#...", ".###....", "........"],
    "9": ["........", ".###....", "#...#...", "#...#...", ".####...", "....#...", ".##.....", "........"],
    # punctuation
    ":": ["........", "........", ".##.....", ".##.....", "........", ".##.....", ".##.....", "........"],
    ".": ["........", "........", "........", "........", "........", ".##.....", ".##.....", "........"],
    ",": ["........", "........", "........", "........", "........", ".##.....", ".##.....", ".#......"],
    "'": [".#......", ".#......", ".#......", "........", "........", "........", "........", "........"],
    "!": ["..#.....", "..#.....", "..#.....", "..#.....", "..#.....", "........", "..#.....", "........"],
    "?": [".###....", "#...#...", "...#....", "..#.....", "..#.....", "........", "..#.....", "........"],
    "-": ["........", "........", "........", ".###....", "........", "........", "........", "........"],
}

# ---------------------------------------------------------------------------
# Messages. Authored as plain strings; the tool word-wraps to the interior
# width and paginates to 4 lines, emitting a byte stream the runtime renders:
#   tile bytes (glyph or $00 space) ... per line, with control codes
#   $FE = newline, $FD = page break (wait for A), $FF = end of message.
# Pages are padded to exactly 4 lines so a new page fully overwrites the last.
# ---------------------------------------------------------------------------
MSG_NEWLINE, MSG_PAGE, MSG_END = 0xFE, 0xFD, 0xFF
TEXT_W, TEXT_H = 30, 4   # interior width / lines per page

MESSAGES = [
    # name, text
    # "\f" forces a page break (press A to advance to the next page).
    ("NPC_GREETING",
     "Hi you!\f"
     "Welcome to the world!"),
    ("SLIME_APPEARS", "A Slime draws near!"),
    ("SLIME_DEFEATED", "The Slime is defeated!"),
    ("NOBODY", "There is no one there."),
]

# Fragments composed with a runtime number into a one-line battle message:
#   <DMG_PRE><number><DMG_POST>  e.g. "The Slime takes 6 damage!"
# Emitted as $FF-terminated tile streams the runtime concatenates.
FRAGMENTS = [
    ("DMG_PRE", "The Slime takes "),
    ("DMG_POST", " damage!"),
    # menu labels
    ("OPT_TALK", "Talk"),
    ("OPT_EQUIP", "Equip"),
    ("WPN0", "Club"),
    ("WPN1", "Sword"),
    ("LBL_ATK", "  ATK "),
    ("LBL_POWER", "Power: "),
]

# ---------------------------------------------------------------------------
# Enemy: authored at 16x16, doubled to 32x32, drawn as background tiles on the
# battle screen (battle palette 1). Value 0 = transparent -> the blue battle
# backdrop shows through, so the blob's silhouette blends cleanly.
#   1 = body, 2 = shading, 3 = eyes/mouth (white).
# ---------------------------------------------------------------------------
ENEMY16 = [
    "0000001111000000",
    "0000011111100000",
    "0000111111110000",
    "0001111111111000",
    "0011111111111100",
    "0011311113111100",
    "0111311113111110",
    "0111111111111110",
    "1111111111111111",
    "1111111111111111",
    "1111122221111111",
    "1111111111111111",
    "0111111111111110",
    "0011111111111100",
    "0000111111110000",
    "0000000000000000",
]

# Where the NPC stands, in 16px grid cells (must match NPC_GX/GY in main.s).
NPC_GX, NPC_GY = 6, 6


def to_chr(rows):
    """Encode one 8x8 tile (rows of digit chars) to 16 planar bytes."""
    p0, p1 = [], []
    for row in rows:
        b0 = b1 = 0
        for px in row:
            v = int(px)
            b0 = (b0 << 1) | (v & 1)
            b1 = (b1 << 1) | ((v >> 1) & 1)
        p0.append(b0)
        p1.append(b1)
    return p0 + p1


def split16(block):
    """Split a 16x16 art block into 4 8x8 tiles ordered TL, TR, BL, BR."""
    return [
        [r[0:8] for r in block[0:8]],
        [r[8:16] for r in block[0:8]],
        [r[0:8] for r in block[8:16]],
        [r[8:16] for r in block[8:16]],
    ]


def mirror_h(block):
    """Horizontally mirror an art block (used to make a left-facing BG view)."""
    return [row[::-1] for row in block]


def mirror_v(block):
    """Vertically mirror an art block."""
    return block[::-1]


def double(block):
    """2x-scale an NxN art block (each pixel becomes 2x2)."""
    out = []
    for row in block:
        big = "".join(c * 2 for c in row)
        out.append(big)
        out.append(big)
    return out


def split_grid(block, n):
    """Split an (8n)x(8n) art block into n*n 8x8 tiles, row-major."""
    tiles = []
    for tr in range(n):
        for tc in range(n):
            tiles.append([r[tc * 8:(tc + 1) * 8] for r in block[tr * 8:(tr + 1) * 8]])
    return tiles


# Dragon-Warrior-style frame: black box with a white double line near the edge,
# rounded corners. '#' = white (value 1), '.' = black (value 0). Only the
# top-left corner and the top/left edges are authored; the rest are mirrored.
WIN_TL_ART = [
    "........",
    "........",
    "..######",
    "..#.....",
    "..#.####",
    "..#.#...",
    "..#.#...",
    "..#.#...",
]
WIN_T_ART = [
    "........",
    "........",
    "########",
    "........",
    "########",
    "........",
    "........",
    "........",
]
WIN_L_ART = [
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
    "..#.#...",
]
WIN_FILL_ART = ["........"] * 8


def to_digits(art):
    """Convert '#'/'.' art into the digit strings to_chr() expects (1=white)."""
    return ["".join("1" if c == "#" else "0" for c in row) for row in art]


# Glyphs that already have 1px-gap vertical strokes (combs); right-dilation
# would blob them, so they are authored pre-thickened and skip the pass.
BOLD_EXEMPT = set("mwMW")


def thicken(art):
    """Faux-bold: extend each stroke one pixel to the right (2px stems)."""
    out = []
    for row in art:
        new = list(row)
        for j in range(1, len(row)):
            if row[j] == "." and row[j - 1] == "#":
                new[j] = "#"
        out.append("".join(new))
    return out


def glyph(ch):
    """Font tile: '#' = white ink (value 1) on '.' = black (value 0)."""
    art = FONT[ch]
    if ch not in BOLD_EXEMPT:
        art = thicken(art)
    return to_digits(art)


def wrap_text(text, width):
    """Greedy word-wrap into a list of lines no wider than `width`."""
    lines, cur = [], ""
    for word in text.split():
        assert len(word) <= width, f"word too long: {word!r}"
        if not cur:
            cur = word
        elif len(cur) + 1 + len(word) <= width:
            cur += " " + word
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines


def encode_message(text, font_id):
    """Wrap + paginate `text` into the runtime byte stream (see MESSAGES).
    A form-feed ("\\f") in the source forces a page break."""
    pages = []
    for segment in text.split("\f"):
        lines = wrap_text(segment, TEXT_W)
        for p in range(0, max(len(lines), 1), TEXT_H):
            pages.append(lines[p:p + TEXT_H])

    out = []
    for pi, page in enumerate(pages):
        page = list(page) + [""] * (TEXT_H - len(page))   # pad to 4 lines
        last_page = pi == len(pages) - 1
        for i, line in enumerate(page):
            for ch in line:
                out.append(0x00 if ch == " " else font_id[ch])
            if i < TEXT_H - 1:
                out.append(MSG_NEWLINE)
            else:
                out.append(MSG_END if last_page else MSG_PAGE)
    return out


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(here, "src")

    # --- assemble the ordered background tile table ---
    font_chars = sorted(FONT.keys())
    font_id = {ch: F_BASE + i for i, ch in enumerate(font_chars)}

    bg = {}
    bg.update(TILES)
    # NPC four facings (left is mirrored from the right-facing "side" art).
    npc_blocks = {
        NPC_DOWN: NPC_VIEWS["down"],
        NPC_UP: NPC_VIEWS["up"],
        NPC_RIGHT: NPC_VIEWS["side"],
        NPC_LEFT: mirror_h(NPC_VIEWS["side"]),
    }
    for base, block in npc_blocks.items():
        for i, tile in enumerate(split16(block)):
            bg[base + i] = tile
    # Window frame: author TL + top/left edges + fill; mirror for the rest.
    tl = to_digits(WIN_TL_ART)
    top = to_digits(WIN_T_ART)
    left = to_digits(WIN_L_ART)
    bg[W_TL] = tl
    bg[W_T] = top
    bg[W_TR] = mirror_h(tl)
    bg[W_L] = left
    bg[W_FILL] = to_digits(WIN_FILL_ART)
    bg[W_R] = mirror_h(left)
    bg[W_BL] = mirror_v(tl)
    bg[W_B] = mirror_v(top)
    bg[W_BR] = mirror_v(mirror_h(tl))
    for ch in font_chars:
        bg[font_id[ch]] = glyph(ch)
    e_base = F_BASE + len(font_chars)          # enemy tiles follow the font
    for i, tile in enumerate(split_grid(double(ENEMY16), 4)):
        bg[e_base + i] = tile

    last_bg = max(bg)
    bg_bytes = []
    for tid in range(last_bg + 1):
        bg_bytes += to_chr(bg.get(tid, ["00000000"] * 8))

    # Hero sprite tiles: down, up, side (left = side H-flipped at draw time).
    hero_bytes = []
    for view in ("down", "up", "side"):
        for tile in split16(HERO_VIEWS[view]):
            hero_bytes += to_chr(tile)

    with open(os.path.join(src, "chr.s"), "w") as f:
        f.write("; chr.s - GENERATED by tools/gen_assets.py. Do not edit by hand.\n")
        f.write("; Pattern table 0: field tiles, NPC (4 facings), window, font, enemy ($00-$%02X).\n" % last_bg)
        f.write("; Pattern table 1 ($1000): hero tiles - down $00, up $04, side $08.\n")
        f.write("; The CHR region fills the remaining 8KB with zero (see nes.cfg).\n\n")
        f.write('.segment "CHARS"\n')
        f.write("    ; --- pattern table 0: background ---\n")
        for i in range(0, len(bg_bytes), 16):
            row = ", ".join(f"${b:02X}" for b in bg_bytes[i:i + 16])
            f.write(f"    .byte {row}   ; bg tile ${i // 16:02X}\n")
        pad = 0x1000 - len(bg_bytes)
        f.write(f"\n    .res ${pad:04X}, $00   ; pad to pattern table 1 ($1000)\n\n")
        f.write("    ; --- pattern table 1: sprites ---\n")
        for i in range(0, len(hero_bytes), 16):
            row = ", ".join(f"${b:02X}" for b in hero_bytes[i:i + 16])
            f.write(f"    .byte {row}   ; hero tile ${i // 16:02X}\n")

    # --- build the field map ---
    W, H = 32, 30
    m = [[T_GRASS] * W for _ in range(H)]
    for x in range(W):
        m[0][x] = T_TREE
        m[H - 1][x] = T_TREE
    for y in range(H):
        m[y][0] = T_TREE
        m[y][W - 1] = T_TREE
    for y in range(3, 8):
        for x in range(3, 9):
            m[y][x] = T_WATER
    for y in range(1, H - 1):
        m[y][16] = T_PATH
    for x in range(1, W - 1):
        m[22][x] = T_PATH
    for x in range(20, 26):
        m[3][x] = T_WALL
        m[7][x] = T_WALL
    for y in range(3, 8):
        m[y][20] = T_WALL
        m[y][25] = T_WALL
    for (x, y) in [(5, 12), (9, 18), (13, 25), (27, 10), (29, 19), (23, 24), (6, 26)]:
        m[y][x] = T_FLOWER
    for (x, y) in [(11, 11), (28, 6), (4, 20), (19, 27), (26, 14), (8, 9)]:
        m[y][x] = T_BUSH

    # stamp the NPC (2x2 background tiles) at its grid cell, in its facing
    npc_base = NPC_FACE[NPC_FACING]
    bx, by = NPC_GX * 2, NPC_GY * 2
    m[by][bx], m[by][bx + 1] = npc_base + 0, npc_base + 1
    m[by + 1][bx], m[by + 1][bx + 1] = npc_base + 2, npc_base + 3

    def palette_of(tile):
        if tile == T_WATER:
            return 1
        if NPC_DOWN <= tile <= NPC_RIGHT + 3:   # any NPC facing tile
            return 2
        return 0

    def attr_table(grid):
        attr = [0] * 64
        for ay in range(8):
            for ax in range(8):
                byte = 0
                for q in range(4):
                    qx, qy = q & 1, q >> 1
                    pal = 0
                    for ty in range(2):
                        for tx in range(2):
                            x = ax * 4 + qx * 2 + tx
                            y = ay * 4 + qy * 2 + ty
                            if 0 <= y < H and 0 <= x < W:
                                pal = max(pal, palette_of(grid[y][x]))
                    byte |= pal << (q * 2)
                attr[ay * 8 + ax] = byte
        return attr

    flat = [m[y][x] for y in range(H) for x in range(W)]
    attr = attr_table(m)

    # --- build the window SHELL: frame + blank interior, 32 wide x 8 tall ---
    # Full-width box at nametable rows 20-27 (so the palette-3 band aligns), with
    # the frame at the very edge. The runtime renders text into the blank
    # interior (rows 22-25), so no text is baked here.
    IN_W = 30
    pad_row = [W_L] + [W_FILL] * IN_W + [W_R]
    winmap = [W_TL] + [W_T] * IN_W + [W_TR]     # row 0: top border
    winmap += pad_row                            # row 1: top padding
    winmap += pad_row * 4                         # rows 2-5: 4 blank text lines
    winmap += pad_row                            # row 6: bottom padding
    winmap += [W_BL] + [W_B] * IN_W + [W_BR]     # row 7: bottom border

    # window draw steps: 4 clear (black) + 1 attribute + 4 content, 64 tiles/step.
    # Transitions route through an all-black region so no tile is ever shown
    # under the wrong palette (black = value 0 is palette-independent).
    win_steps = 9

    with open(os.path.join(src, "field.s"), "w") as f:
        f.write("; field.s - GENERATED by tools/gen_assets.py. Do not edit by hand.\n")
        f.write("; One-screen field map + attribute table, and the window shell.\n\n")
        f.write(".export fieldmap, fieldattr, winmap\n\n")
        f.write('.segment "RODATA"\n')
        f.write(fmt_bytes("fieldmap", flat, 32) + "\n\n")
        f.write(fmt_bytes("fieldattr", attr, 16) + "\n\n")
        f.write(fmt_bytes("winmap", winmap, 32) + "\n")

    # --- messages + fragments ---
    encoded = [(name, encode_message(text, font_id)) for name, text in MESSAGES]
    frags = [(name, [0x00 if c == " " else font_id[c] for c in text] + [0xFF])
             for name, text in FRAGMENTS]
    with open(os.path.join(src, "messages.s"), "w") as f:
        f.write("; messages.s - GENERATED by tools/gen_assets.py. Do not edit by hand.\n")
        f.write("; msg_table: word pointers indexed by MSG_* (see tiles.inc).\n")
        f.write("; frag_*: $FF-terminated tile streams for runtime composition.\n\n")
        f.write(".export msg_table")
        for name, _ in frags:
            f.write(f", frag_{name}")
        f.write("\n\n")
        f.write('.segment "RODATA"\n')
        f.write("msg_table:\n")
        for name, _ in encoded:
            f.write(f"    .word msg_{name}\n")
        f.write("\n")

        def emit_bytes(label, data):
            f.write(f"{label}:\n")
            for i in range(0, len(data), 16):
                row = ", ".join(f"${b:02X}" for b in data[i:i + 16])
                f.write(f"    .byte {row}\n")
            f.write("\n")

        for name, data in encoded:
            emit_bytes("msg_" + name, data)
        for name, data in frags:
            emit_bytes("frag_" + name, data)

    # tile-index constants consumed by main.s (so nothing is hardcoded there)
    with open(os.path.join(src, "tiles.inc"), "w") as f:
        f.write("; tiles.inc - GENERATED by tools/gen_assets.py. Do not edit by hand.\n\n")
        f.write("; Sprite tiles (pattern table 1), 4 tiles per facing.\n")
        f.write(f"HERO_DOWN_TILE = ${HERO_DOWN:02X}\n")
        f.write(f"HERO_UP_TILE   = ${HERO_UP:02X}\n")
        f.write(f"HERO_SIDE_TILE = ${HERO_SIDE:02X}\n\n")
        f.write("; Background tiles (pattern table 0).\n")
        f.write(f"TILE_NPC_LO = ${NPC_DOWN:02X}   ; first NPC tile (all facings)\n")
        f.write(f"TILE_NPC_HI = ${NPC_RIGHT + 3:02X}   ; last NPC tile (solid range)\n")
        f.write(f"ENEMY_TILE_BASE = ${e_base:02X}\n")
        f.write(f"ARROW_TILE = ${font_id[ARROW]:02X}   ; 'more text' prompt\n")
        f.write(f"WIN_BOTTOM_TILE = ${W_B:02X}   ; bottom-border tile (restores under the prompt)\n")
        f.write(f"DIGIT_TILE = ${font_id['0']:02X}   ; '0'; digit d -> DIGIT_TILE + d\n")
        f.write(f"CURSOR_TILE = ${font_id[CURSOR]:02X}   ; menu cursor (right triangle)\n\n")
        f.write("; Text window: full-width box at nametable rows 20-27.\n")
        f.write(f"WIN_STEPS = {win_steps}\n")
        f.write(f"TEXT_COLS = {TEXT_W}\n")
        f.write(f"TEXT_LINES = {TEXT_H}\n")
        f.write("; Message control codes and ids.\n")
        f.write(f"MSG_NEWLINE = ${MSG_NEWLINE:02X}\n")
        f.write(f"MSG_PAGE    = ${MSG_PAGE:02X}\n")
        f.write(f"MSG_END     = ${MSG_END:02X}\n")
        for i, (name, _) in enumerate(MESSAGES):
            f.write(f"MSG_{name} = {i}\n")

    # console preview
    glyphs = {T_GRASS: ".", T_FLOWER: ",", T_PATH: ":", T_TREE: "T",
              T_WALL: "#", T_BUSH: "o", T_WATER: "~"}
    print("Field map preview (N = NPC, facing %s):" % NPC_FACING)
    for y in range(H):
        line = ""
        for x in range(W):
            t = m[y][x]
            line += "N" if NPC_DOWN <= t <= NPC_RIGHT + 3 else glyphs.get(t, "?")
        print(line)


def fmt_bytes(label, data, per_line):
    out = [f"{label}:"]
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"${b:02X}" for b in data[i:i + per_line])
        out.append(f"    .byte {chunk}")
    return "\n".join(out)


if __name__ == "__main__":
    main()
