; chr.s - GENERATED by tools/gen_assets.py. Do not edit by hand.
; Pattern table 0: field tiles, NPC (4 facings), window, font, enemy ($00-$37).
; Pattern table 1 ($1000): hero tiles - down $00, up $04, side $08.
; The CHR region fills the remaining 8KB with zero (see nes.cfg).

.segment "CHARS"
    ; --- pattern table 0: background ---
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $00
    .byte $F7, $FF, $7D, $FF, $DF, $FF, $FD, $7F, $08, $00, $82, $00, $20, $00, $02, $80   ; bg tile $01
    .byte $FF, $E7, $DB, $D7, $DB, $E7, $FF, $FF, $00, $18, $3C, $3C, $3C, $18, $00, $00   ; bg tile $02
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $DF, $FD, $FF, $BF, $FB, $FF, $EF   ; bg tile $03
    .byte $81, $00, $24, $00, $24, $00, $BD, $FF, $7E, $FF, $FF, $FF, $FF, $FF, $7E, $3C   ; bg tile $04
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $55, $FF, $FF, $AA, $FF, $FF   ; bg tile $05
    .byte $FF, $C3, $81, $81, $81, $C3, $FF, $FF, $00, $3C, $7E, $7E, $7E, $3C, $00, $00   ; bg tile $06
    .byte $FF, $99, $FF, $66, $FF, $99, $FF, $66, $00, $66, $00, $99, $00, $66, $00, $99   ; bg tile $07
    .byte $0F, $18, $30, $36, $30, $30, $18, $3F, $00, $07, $0F, $0F, $0F, $0F, $07, $00   ; bg tile $08
    .byte $E0, $30, $18, $58, $18, $18, $30, $F0, $00, $C0, $E0, $E0, $E0, $E0, $C0, $00   ; bg tile $09
    .byte $7F, $7F, $7F, $7F, $7F, $7F, $3F, $1F, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $0A
    .byte $F8, $F8, $F8, $F8, $F8, $F8, $F0, $E0, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $0B
    .byte $0F, $18, $30, $30, $30, $30, $18, $3F, $00, $07, $0F, $0F, $0F, $0F, $07, $00   ; bg tile $0C
    .byte $E0, $30, $18, $18, $18, $18, $30, $F0, $00, $C0, $E0, $E0, $E0, $E0, $C0, $00   ; bg tile $0D
    .byte $7F, $7F, $7F, $7F, $7F, $7F, $3F, $1F, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $0E
    .byte $F8, $F8, $F8, $F8, $F8, $F8, $F0, $E0, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $0F
    .byte $03, $04, $04, $05, $04, $04, $04, $07, $00, $03, $03, $03, $0F, $03, $03, $00   ; bg tile $10
    .byte $F0, $08, $04, $04, $04, $04, $08, $F8, $00, $F0, $F8, $F8, $F8, $F8, $F0, $00   ; bg tile $11
    .byte $0F, $0F, $0F, $0F, $0F, $0F, $07, $03, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $12
    .byte $FC, $FC, $FC, $FC, $FC, $FC, $F8, $F0, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $13
    .byte $0F, $10, $20, $20, $20, $20, $10, $1F, $00, $0F, $1F, $1F, $1F, $1F, $0F, $00   ; bg tile $14
    .byte $C0, $20, $20, $A0, $20, $20, $20, $E0, $00, $C0, $C0, $C0, $F0, $C0, $C0, $00   ; bg tile $15
    .byte $3F, $3F, $3F, $3F, $3F, $3F, $1F, $0F, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $16
    .byte $F0, $F0, $F0, $F0, $F0, $F0, $E0, $C0, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $17
    .byte $00, $7F, $7F, $7F, $7F, $7F, $7F, $7F, $FF, $80, $80, $80, $80, $80, $80, $80   ; bg tile $18
    .byte $00, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00   ; bg tile $19
    .byte $00, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FF, $01, $01, $01, $01, $01, $01, $01   ; bg tile $1A
    .byte $7F, $7F, $7F, $7F, $7F, $7F, $7F, $7F, $80, $80, $80, $80, $80, $80, $80, $80   ; bg tile $1B
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $1C
    .byte $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $01, $01, $01, $01, $01, $01, $01, $01   ; bg tile $1D
    .byte $7F, $7F, $7F, $7F, $7F, $7F, $7F, $00, $80, $80, $80, $80, $80, $80, $80, $FF   ; bg tile $1E
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00, $FF   ; bg tile $1F
    .byte $FE, $FE, $FE, $FE, $FE, $FE, $FE, $00, $01, $01, $01, $01, $01, $01, $01, $FF   ; bg tile $20
    .byte $EF, $EF, $EF, $EF, $EF, $FF, $EF, $FF, $10, $10, $10, $10, $10, $00, $10, $00   ; bg tile $21
    .byte $FF, $83, $BF, $87, $BF, $BF, $83, $FF, $00, $7C, $40, $78, $40, $40, $7C, $00   ; bg tile $22
    .byte $FF, $BB, $BB, $83, $BB, $BB, $BB, $FF, $00, $44, $44, $7C, $44, $44, $44, $00   ; bg tile $23
    .byte $FF, $BF, $BF, $BF, $BF, $BF, $83, $FF, $00, $40, $40, $40, $40, $40, $7C, $00   ; bg tile $24
    .byte $FF, $C7, $BB, $BB, $BB, $BB, $C7, $FF, $00, $38, $44, $44, $44, $44, $38, $00   ; bg tile $25
    .byte $FF, $87, $BB, $87, $AF, $B7, $BB, $FF, $00, $78, $44, $78, $50, $48, $44, $00   ; bg tile $26
    .byte $FF, $83, $EF, $EF, $EF, $EF, $EF, $FF, $00, $7C, $10, $10, $10, $10, $10, $00   ; bg tile $27
    .byte $00, $00, $00, $00, $00, $00, $03, $03, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $28
    .byte $0F, $0F, $3F, $3F, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $29
    .byte $F0, $F0, $FC, $FC, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $2A
    .byte $00, $00, $00, $00, $00, $00, $C0, $C0, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $2B
    .byte $0F, $0F, $0F, $0F, $3F, $3F, $3F, $3F, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $2C
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $C0, $C0, $C0, $C0, $00, $00   ; bg tile $2D
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $30, $30, $30, $30, $00, $00   ; bg tile $2E
    .byte $F0, $F0, $F0, $F0, $FC, $FC, $FC, $FC, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $2F
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $30
    .byte $FF, $FF, $FF, $FF, $C0, $C0, $FF, $FF, $00, $00, $00, $00, $3F, $3F, $00, $00   ; bg tile $31
    .byte $FF, $FF, $FF, $FF, $3F, $3F, $FF, $FF, $00, $00, $00, $00, $C0, $C0, $00, $00   ; bg tile $32
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $33
    .byte $3F, $3F, $0F, $0F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $34
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $35
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $36
    .byte $FC, $FC, $F0, $F0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $37

    .res $0C80, $00   ; pad to pattern table 1 ($1000)

    ; --- pattern table 1: sprites ---
    .byte $07, $08, $10, $12, $10, $10, $08, $07, $00, $07, $0F, $0F, $0F, $0F, $07, $00   ; hero tile $00
    .byte $E0, $10, $08, $48, $08, $08, $10, $E0, $00, $E0, $F0, $F0, $F0, $F0, $E0, $00   ; hero tile $01
    .byte $1F, $3F, $3F, $3F, $1F, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $02
    .byte $F8, $FC, $FC, $FC, $F8, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $03
    .byte $07, $08, $10, $10, $10, $10, $08, $07, $00, $07, $0F, $0F, $0F, $0F, $07, $00   ; hero tile $04
    .byte $E0, $10, $08, $08, $08, $08, $10, $E0, $00, $E0, $F0, $F0, $F0, $F0, $E0, $00   ; hero tile $05
    .byte $1F, $3F, $3F, $3F, $1F, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $06
    .byte $F8, $FC, $FC, $FC, $F8, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $07
    .byte $0F, $10, $20, $20, $20, $20, $10, $0F, $00, $0F, $1F, $1F, $1F, $1F, $0F, $00   ; hero tile $08
    .byte $C0, $20, $10, $50, $10, $10, $20, $C0, $00, $C0, $E0, $E0, $F8, $E0, $C0, $00   ; hero tile $09
    .byte $1F, $3F, $3F, $3F, $1F, $1C, $1C, $1C, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $0A
    .byte $E0, $F0, $F0, $F0, $E0, $C0, $C0, $C0, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $0B
