; chr.s - GENERATED by tools/gen_assets.py. Do not edit by hand.
; Pattern table 0: background field tiles ($00-$07).
; Pattern table 1 ($1000): hero metasprite tiles ($00-$03).
; The CHR region fills the remaining 8KB with zero (see nes.cfg).

.segment "CHARS"
    ; --- pattern table 0: background ---
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; bg tile $00
    .byte $F7, $FF, $7D, $FF, $DF, $FF, $FD, $7F, $08, $00, $82, $00, $20, $00, $02, $80   ; bg tile $01
    .byte $FF, $E7, $DB, $D7, $DB, $E7, $FF, $FF, $00, $18, $3C, $3C, $3C, $18, $00, $00   ; bg tile $02
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $DF, $FD, $FF, $BF, $FB, $FF, $EF   ; bg tile $03
    .byte $81, $00, $24, $00, $24, $00, $BD, $FF, $7E, $FF, $FF, $FF, $FF, $FF, $7E, $3C   ; bg tile $04
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $55, $FF, $FF, $AA, $FF, $FF   ; bg tile $05
    .byte $FF, $C3, $81, $81, $81, $C3, $FF, $FF, $00, $3C, $7E, $7E, $7E, $3C, $00, $00   ; bg tile $06
    .byte $FF, $99, $FF, $66, $FF, $99, $FF, $66, $00, $66, $00, $99, $00, $66, $00, $99   ; bg tile $07

    .res $0F80, $00   ; pad to pattern table 1 ($1000)

    ; --- pattern table 1: sprites ---
    .byte $07, $08, $10, $12, $10, $10, $08, $07, $00, $07, $0F, $0F, $0F, $0F, $07, $00   ; hero tile $00
    .byte $E0, $10, $08, $48, $08, $08, $10, $E0, $00, $E0, $F0, $F0, $F0, $F0, $E0, $00   ; hero tile $01
    .byte $1F, $3F, $3F, $3F, $1F, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $02
    .byte $F8, $FC, $FC, $FC, $F8, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00   ; hero tile $03
