; chr.s - GENERATED by tools/gen_assets.py. Do not edit by hand.
; Background field tiles for pattern table 0. CHR region fill
; pads the rest of the 8KB to zero (see nes.cfg).

.segment "CHARS"
    ; tiles $00-$07
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00   ; tile $00
    .byte $F7, $FF, $7D, $FF, $DF, $FF, $FD, $7F, $08, $00, $82, $00, $20, $00, $02, $80   ; tile $01
    .byte $FF, $E7, $DB, $D7, $DB, $E7, $FF, $FF, $00, $18, $3C, $3C, $3C, $18, $00, $00   ; tile $02
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $DF, $FD, $FF, $BF, $FB, $FF, $EF   ; tile $03
    .byte $81, $00, $24, $00, $24, $00, $BD, $FF, $7E, $FF, $FF, $FF, $FF, $FF, $7E, $3C   ; tile $04
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $55, $FF, $FF, $AA, $FF, $FF   ; tile $05
    .byte $FF, $C3, $81, $81, $81, $C3, $FF, $FF, $00, $3C, $7E, $7E, $7E, $3C, $00, $00   ; tile $06
    .byte $FF, $99, $FF, $66, $FF, $99, $FF, $66, $00, $66, $00, $99, $00, $66, $00, $99   ; tile $07
