; messages.s - GENERATED by tools/gen_assets.py. Do not edit by hand.
; msg_table: word pointers indexed by MSG_* (see tiles.inc).
; frag_*: $FF-terminated tile streams for runtime composition.

.export msg_table, frag_DMG_PRE, frag_DMG_POST

.segment "RODATA"
msg_table:
    .word msg_NPC_GREETING
    .word msg_SLIME_APPEARS
    .word msg_SLIME_DEFEATED

msg_NPC_GREETING:
    .byte $37, $5E, $50, $5E, $55, $4F, $57, $25, $00, $58, $55, $5F, $60, $51, $5A, $00
    .byte $5A, $5B, $63, $00, $60, $5B, $00, $59, $65, $FE, $63, $5B, $5E, $50, $5F, $27
    .byte $00, $3B, $5A, $00, $4D, $53, $51, $5F, $00, $5C, $4D, $5F, $60, $25, $00, $4D
    .byte $00, $54, $51, $5E, $5B, $FE, $5F, $51, $4D, $58, $51, $50, $00, $60, $54, $51
    .byte $00, $50, $51, $59, $5B, $5A, $00, $63, $55, $60, $54, $00, $4D, $00, $34, $4D
    .byte $58, $58, $FE, $5B, $52, $00, $3E, $55, $53, $54, $60, $27, $00, $45, $51, $51
    .byte $57, $00, $55, $60, $25, $00, $4E, $5E, $4D, $62, $51, $00, $5B, $5A, $51, $25
    .byte $FD, $4D, $5A, $50, $00, $52, $4D, $4F, $51, $00, $60, $54, $51, $00, $50, $4D
    .byte $5E, $57, $5A, $51, $5F, $5F, $00, $60, $54, $4D, $60, $FE, $63, $4D, $57, $51
    .byte $5F, $00, $5B, $5A, $4F, $51, $00, $59, $5B, $5E, $51, $27, $FE, $FE, $FF

msg_SLIME_APPEARS:
    .byte $33, $00, $45, $58, $55, $59, $51, $00, $50, $5E, $4D, $63, $5F, $00, $5A, $51
    .byte $4D, $5E, $23, $FE, $FE, $FE, $FF

msg_SLIME_DEFEATED:
    .byte $46, $54, $51, $00, $45, $58, $55, $59, $51, $00, $55, $5F, $00, $50, $51, $52
    .byte $51, $4D, $60, $51, $50, $23, $FE, $FE, $FE, $FF

frag_DMG_PRE:
    .byte $46, $54, $51, $00, $45, $58, $55, $59, $51, $00, $60, $4D, $57, $51, $5F, $00
    .byte $FF

frag_DMG_POST:
    .byte $00, $50, $4D, $59, $4D, $53, $51, $23, $FF

