; messages.s - GENERATED by tools/gen_assets.py. Do not edit by hand.
; msg_table: word pointers indexed by MSG_* (see tiles.inc).
; frag_*: $FF-terminated tile streams for runtime composition.

.export msg_table, frag_DMG_PRE, frag_DMG_POST, frag_OPT_TALK, frag_OPT_EQUIP, frag_WPN0, frag_WPN1, frag_LBL_ATK, frag_LBL_POWER

.segment "RODATA"
msg_table:
    .word msg_NPC_GREETING
    .word msg_SLIME_APPEARS
    .word msg_SLIME_DEFEATED
    .word msg_NOBODY

msg_NPC_GREETING:
    .byte $3C, $57, $00, $3F, $5C, $5D, $4F, $56, $00, $62, $56, $57, $61, $00, $48, $4F
    .byte $53, $59, $5D, $FE, $FE, $FE, $FD, $4B, $53, $5A, $51, $5D, $5B, $53, $00, $62
    .byte $5D, $00, $62, $56, $53, $00, $61, $53, $66, $67, $00, $68, $5D, $5C, $53, $FE
    .byte $FE, $FE, $FF

msg_SLIME_APPEARS:
    .byte $35, $00, $47, $5A, $57, $5B, $53, $00, $52, $60, $4F, $65, $61, $00, $5C, $53
    .byte $4F, $60, $24, $FE, $FE, $FE, $FF

msg_SLIME_DEFEATED:
    .byte $48, $56, $53, $00, $47, $5A, $57, $5B, $53, $00, $57, $61, $00, $52, $53, $54
    .byte $53, $4F, $62, $53, $52, $24, $FE, $FE, $FE, $FF

msg_NOBODY:
    .byte $48, $56, $53, $60, $53, $00, $57, $61, $00, $5C, $5D, $00, $5D, $5C, $53, $00
    .byte $62, $56, $53, $60, $53, $28, $FE, $FE, $FE, $FF

frag_DMG_PRE:
    .byte $48, $56, $53, $00, $47, $5A, $57, $5B, $53, $00, $62, $4F, $59, $53, $61, $00
    .byte $FF

frag_DMG_POST:
    .byte $00, $52, $4F, $5B, $4F, $55, $53, $24, $FF

frag_OPT_TALK:
    .byte $48, $4F, $5A, $59, $FF

frag_OPT_EQUIP:
    .byte $39, $5F, $63, $57, $5E, $FF

frag_WPN0:
    .byte $37, $5A, $63, $50, $FF

frag_WPN1:
    .byte $47, $65, $5D, $60, $52, $FF

frag_LBL_ATK:
    .byte $00, $00, $35, $48, $3F, $00, $FF

frag_LBL_POWER:
    .byte $44, $5D, $65, $53, $60, $33, $00, $FF

