; messages.s - GENERATED by tools/gen_assets.py. Do not edit by hand.
; msg_table: word pointers indexed by MSG_* (see tiles.inc).
; frag_*: $FF-terminated tile streams for runtime composition.

.export msg_table, frag_DMG_PRE, frag_DMG_POST, frag_OPT_TALK, frag_OPT_EQUIP, frag_WPN0, frag_WPN1, frag_LBL_ATK, frag_LBL_POWER

.segment "RODATA"
msg_table:
    .word msg_NPC_GREETING
    .word msg_SLIME_APPEARS
    .word msg_SLIME_DEFEATED
    .word msg_NOBODY

msg_NPC_GREETING:
    .byte $39, $60, $52, $60, $57, $51, $59, $26, $00, $5A, $57, $61, $62, $53, $5C, $00
    .byte $5C, $5D, $65, $00, $62, $5D, $00, $5B, $67, $FE, $65, $5D, $60, $52, $61, $28
    .byte $00, $3D, $5C, $00, $4F, $55, $53, $61, $00, $5E, $4F, $61, $62, $26, $00, $4F
    .byte $00, $56, $53, $60, $5D, $FE, $61, $53, $4F, $5A, $53, $52, $00, $62, $56, $53
    .byte $00, $52, $53, $5B, $5D, $5C, $00, $65, $57, $62, $56, $00, $4F, $00, $36, $4F
    .byte $5A, $5A, $FE, $5D, $54, $00, $40, $57, $55, $56, $62, $28, $00, $47, $53, $53
    .byte $59, $00, $57, $62, $26, $00, $50, $60, $4F, $64, $53, $00, $5D, $5C, $53, $26
    .byte $FD, $4F, $5C, $52, $00, $54, $4F, $51, $53, $00, $62, $56, $53, $00, $52, $4F
    .byte $60, $59, $5C, $53, $61, $61, $00, $62, $56, $4F, $62, $FE, $65, $4F, $59, $53
    .byte $61, $00, $5D, $5C, $51, $53, $00, $5B, $5D, $60, $53, $28, $FE, $FE, $FF

msg_SLIME_APPEARS:
    .byte $35, $00, $47, $5A, $57, $5B, $53, $00, $52, $60, $4F, $65, $61, $00, $5C, $53
    .byte $4F, $60, $24, $FE, $FE, $FE, $FF

msg_SLIME_DEFEATED:
    .byte $48, $56, $53, $00, $47, $5A, $57, $5B, $53, $00, $57, $61, $00, $52, $53, $54
    .byte $53, $4F, $62, $53, $52, $24, $FE, $FE, $FE, $FF

msg_NOBODY:
    .byte $48, $56, $53, $60, $53, $00, $57, $61, $00, $5C, $5D, $00, $5D, $5C, $53, $00
    .byte $62, $56, $53, $60, $53, $28, $FE, $FE, $FE, $FF

frag_DMG_PRE:
    .byte $48, $56, $53, $00, $47, $5A, $57, $5B, $53, $00, $62, $4F, $59, $53, $61, $00
    .byte $FF

frag_DMG_POST:
    .byte $00, $52, $4F, $5B, $4F, $55, $53, $24, $FF

frag_OPT_TALK:
    .byte $48, $4F, $5A, $59, $FF

frag_OPT_EQUIP:
    .byte $39, $5F, $63, $57, $5E, $FF

frag_WPN0:
    .byte $37, $5A, $63, $50, $FF

frag_WPN1:
    .byte $47, $65, $5D, $60, $52, $FF

frag_LBL_ATK:
    .byte $00, $00, $35, $48, $3F, $00, $FF

frag_LBL_POWER:
    .byte $44, $5D, $65, $53, $60, $33, $00, $FF

